/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-09 06:52:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user.mykurly.default_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainTop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"myPageTop\" class=\"page_aticle mypage_top\">\r\n");
      out.write("	<h2 class=\"screen_out\">마이페이지</h2>\r\n");
      out.write("	<div class=\"mypagetop_user\">\r\n");
      out.write("		<div class=\"inner_mypagetop\">\r\n");
      out.write("			<div class=\"grade_user\">\r\n");
      out.write("				<div class=\"grade_wrap\">\r\n");
      out.write("					<div class=\"grade_logo class0\">일반</div>\r\n");
      out.write("					<strong class=\"name\">홍길동님</strong>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"grade_bnenfit\">\r\n");
      out.write("					<div class=\"benefit\">\r\n");
      out.write("						<strong class=\"tit\"> </strong> 적립 0.5%\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"benefit\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"next\">\r\n");
      out.write("					<a href=\"#none\" class=\"total_grade\"> 전체등급 보기 </a> \r\n");
      out.write("					<a href=\"#none\" class=\"next_month\"> 다음 달 예상등급 보기 </a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"list_mypage\">\r\n");
      out.write("				<div class=\"list\">\r\n");
      out.write("					<a href=\"#none\" class=\"link_wrap\">\r\n");
      out.write("						<div class=\"link_title\">적립금\r\n");
      out.write("							<img src=\"https://res.kurly.com/kurly/ico/2021/arrow_right_gray_56_56.png\" alt=\"\" class=\"arrow_right\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"spacer\"></div>\r\n");
      out.write("							<p class=\"info\"> \r\n");
      out.write("								0원 <span class=\"expire\"> 소멸 예정 0 원 </span>\r\n");
      out.write("							</p>\r\n");
      out.write("					</a> \r\n");
      out.write("					\r\n");
      out.write("					<a href=\"#none\" class=\"link_wrap\">\r\n");
      out.write("						<div class=\"link_title\">쿠폰\r\n");
      out.write("							<img src=\"https://res.kurly.com/kurly/ico/2021/arrow_right_gray_56_56.png\" alt=\"\" class=\"arrow_right\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"spacer\"></div>\r\n");
      out.write("						<p class=\"info\">1 개</p>\r\n");
      out.write("					</a> \r\n");
      out.write("					\r\n");
      out.write("					<a href=\"#none\" class=\"link_wrap\">\r\n");
      out.write("						<div class=\"link_title\"> 컬리 퍼플 박스 \r\n");
      out.write("							<img src=\"https://res.kurly.com/kurly/ico/2021/arrow_right_gray_56_56.png\" alt=\"\" class=\"arrow_right\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"spacer\"></div>\r\n");
      out.write("						<p class=\"info\">알아보기</p>\r\n");
      out.write("					</a> \r\n");
      out.write("					\r\n");
      out.write("					<a href=\"/shop/mypage/kurlypass.php\" class=\"link_wrap\">\r\n");
      out.write("						<div class=\"link_title\">컬리패스 \r\n");
      out.write("							<img src=\"https://res.kurly.com/kurly/ico/2021/arrow_right_gray_56_56.png\" alt=\"\" class=\"arrow_right\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"spacer\"></div>\r\n");
      out.write("						<p class=\"info\">알아보기</p></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a href=\"https://www.kurly.com/shop/main/html.php?htmid=event/kurly.htm&amp;name=friend\" class=\"bnr_event\"\r\n");
      out.write("			style=\"background-image: url(&quot;//img-cf.kurly.com/shop/data/skin/designgj/img/banner/72925f3329df3e5b2c258a355623fc74.jpg&quot;);\"><img\r\n");
      out.write("			src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXcAAAA8CAQAAAA3ITJuAAAAAXNSR0IArs4c6QAAAEJJREFUeAHtwQENAAAAwiD7p34ON2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcCKwBAABQveChQAAAABJRU5ErkJggg==\"\r\n");
      out.write("			alt=\"할인혜택보러가기\"></a> <!-- 배너 -->\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
