/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-12 09:12:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user.mykurly;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class infoModify1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/secondk/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/marketKurlyty/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1632676361414L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/top.jsp", out, false);
      out.write("<!-- 기본 필요 meta, css는 include로 받아옴 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 여기부터 해당 페이지의 css 추가하면 됨-->\r\n");
      out.write("<link rel=\"styleSheet\" href=\"style/ItemListStyle.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function formCheck(){\r\n");
      out.write("   \r\n");
      out.write("   if(document.confirmForm.user_id.value==\"\"){\r\n");
      out.write("		alert(\"아이디를 입력하세요.\");\r\n");
      out.write("		document.confirmForm.user_id.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("   if(document.confirmForm.user_pw.value==\"\"){\r\n");
      out.write("		alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("		document.confirmForm.user_pw.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("   document.confirmForm.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body class=\"main-index\" oncontextmenu=\"return false\"\r\n");
      out.write("	ondragstart=\"return false\" onselectstart=\"return !disableSelection\">\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrap\" class=\"\">\r\n");
      out.write("		<div id=\"pos_scroll\"></div>\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/header.jsp", out, false);
      out.write("<!-- header부분 -->\r\n");
      out.write("			<div id=\"main\">\r\n");
      out.write("				<div id=\"content\">\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/sidemenu.jsp", out, false);
      out.write("<!-- 오른쪽 스크롤메뉴 부분 -->\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "default/mainTop.jsp", out, false);
      out.write("<!-- mypage상단부분 -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"page_aticle aticle_type2\">\r\n");
      out.write("						<!-- Main 시작 -->\r\n");
      out.write("						");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "default/mainLeft.jsp", out, false);
      out.write("\r\n");
      out.write("						<!-- Mainleft -->\r\n");
      out.write("						<div class=\"page_aticle aticle_type2\">\r\n");
      out.write("							<!-- MainCenter 시작 -->\r\n");
      out.write("\r\n");
      out.write("							<div class=\"page_section section_myinfo\">\r\n");
      out.write("								<!-- 비밀번호 입력전 -->\r\n");
      out.write("								<div class=\"head_aticle\">\r\n");
      out.write("									<h2 class=\"tit\">개인 정보 수정</h2>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<div class=\"type_form member_join member_pw\">\r\n");
      out.write("									<div class=\"field_pw\">\r\n");
      out.write("										<h3 class=\"tit\">비밀번호 재확인</h3>\r\n");
      out.write("										<p class=\"sub\">회원님의 정보를 안전하게 보호하기 위해 비밀번호를 다시 한번 확인해주세요.</p>\r\n");
      out.write("\r\n");
      out.write("										<form name=\"confirmForm\" method=\"post\" action=\"infoModify2.do\">\r\n");
      out.write("											<table class=\"tbl_comm\">\r\n");
      out.write("												<tbody>\r\n");
      out.write("													<tr class=\"fst\">\r\n");
      out.write("														<th>아이디</th>\r\n");
      out.write("														<td><input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"user_id\" id=\"user_id\" name=\"user_id\"\r\n");
      out.write("																readonly=\"readonly\">\r\n");
      out.write("															<!-- readonly=\"\" --></td>\r\n");
      out.write("													</tr>\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th>비밀번호</th>\r\n");
      out.write("														<td> <input type=\"password\"	class=\"user_pw\" id=\"user_pw\" name=\"user_pw\"></td>\r\n");
      out.write("													</tr>\r\n");
      out.write("												</tbody>\r\n");
      out.write("											</table>\r\n");
      out.write("											<button type=\"button\" class=\"btn active\" onclick=\"formCheck()\">확인</button>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- MainCenter 끝 -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Main 끝 -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/footer.jsp", out, false);
      out.write("<!-- footer부분 -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<a href=\"#top\" id=\"pageTop\">맨 위로가기</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<iframe name=\"ifrmHidden\" id=\"ifrmHidden\" src=\"about:blank\"\r\n");
      out.write("		style=\"display: none; width: 100%; height: 600px;\"></iframe>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
