/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-05 12:49:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user.customerCenter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/secondk/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/marketKurlyty/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/secondk/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/marketKurlyty/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1632676361414L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setAttribute("notice_serial", "30");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/top.jsp", out, false);
      out.write("<!-- 기본 필요 meta, css는 include로 받아옴 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 여기부터 해당 페이지의 css 추가하면 됨-->\r\n");
      out.write("<link rel=\"styleSheet\" href=\"style/ItemListStyle.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".notice .layout-pagination {\r\n");
      out.write("	margin: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".eng2 {\r\n");
      out.write("	color: #939393\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".xans-board-listheader {\r\n");
      out.write("	font-size: 12px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"tit_page\">\r\n");
      out.write("		<h2 class=\"tit\">공지사항</h2>\r\n");
      out.write("		<p class=\"sub\">컬리의 새로운 소식들과 유용한 정보들을 한곳에서 확인하세요.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"main\">\r\n");
      out.write("			<div class=\"layout-wrapper\">\r\n");
      out.write("				<div class=\"xans-element- xans-myshop xans-myshop-couponserial \">\r\n");
      out.write("					<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<table width=\"100%\">\r\n");
      out.write("										<tbody>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>\r\n");
      out.write("													<table class=\"boardView\" width=\"100%\">\r\n");
      out.write("														<tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("															<tr>\r\n");
      out.write("																<th scope=\"row\" style=\"border: none;\">제목</th>\r\n");
      out.write("																<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.notice_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("															</tr>\r\n");
      out.write("															<tr>\r\n");
      out.write("																<th scope=\"row\">작성자</th>\r\n");
      out.write("																<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.notice_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("															</tr>\r\n");
      out.write("															<tr class=\"etcArea\">\r\n");
      out.write("																<td colspan=\"2\">\r\n");
      out.write("																	<ul>\r\n");
      out.write("																		<li class=\"date \"><strong class=\"th\">작성일</strong>\r\n");
      out.write("																			<span class=\"td\">");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("</span></li>\r\n");
      out.write("																		<li class=\"hit \"><strong class=\"th\">조회수</strong>\r\n");
      out.write("																			<span class=\"td\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.notice_hit }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("																	</ul>\r\n");
      out.write("																</td>\r\n");
      out.write("															</tr>\r\n");
      out.write("														</tbody>\r\n");
      out.write("													</table>\r\n");
      out.write("												</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td align=\"right\" class=\"eng\" style=\"padding: 5px;\"></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td style=\"padding: 10px;\" height=\"200\" valign=\"top\"\r\n");
      out.write("													id=\"contents\">\r\n");
      out.write("													<table width=\"100%\" style=\"table-layout: fixed\">\r\n");
      out.write("														<tbody>\r\n");
      out.write("															<tr>\r\n");
      out.write("																<td class=\"board_view_content\"\r\n");
      out.write("																	style=\"word-wrap: break-word; word-break: break-all\"\r\n");
      out.write("																	id=\"contents_1119\" valign=\"top\"><div>\r\n");
      out.write("																		<span\r\n");
      out.write("																			style=\"font-family: Arial; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);\">\r\n");
      out.write("																		</span>\r\n");
      out.write("																	</div>\r\n");
      out.write("																	<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.notice_content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("																		<span\r\n");
      out.write("																			style=\"font-family: Arial; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);\"><br></span>\r\n");
      out.write("																	</div></td>\r\n");
      out.write("															</tr>\r\n");
      out.write("\r\n");
      out.write("														</tbody>\r\n");
      out.write("													</table>\r\n");
      out.write("												</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td height=\"1\" bgcolor=\"#f4f4f4\"></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("									<br>\r\n");
      out.write("									<table width=\"100%\" style=\"table-layout: fixed\" cellpadding=\"0\"\r\n");
      out.write("										cellspacing=\"0\">\r\n");
      out.write("										<tbody>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td align=\"center\" style=\"padding-top: 10px;\">\r\n");
      out.write("													<table width=\"100%\">\r\n");
      out.write("														<tbody>\r\n");
      out.write("															<tr>\r\n");
      out.write("																<td align=\"right\"><a href=\"notice.do\"><span\r\n");
      out.write("																		class=\"bhs_button yb\" style=\"float: none;\">목록</span></a></td>\r\n");
      out.write("															</tr>\r\n");
      out.write("														</tbody>\r\n");
      out.write("													</table>\r\n");
      out.write("												</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("									<div\r\n");
      out.write("										class=\"xans-element- xans-board xans-board-movement-1002 xans-board-movement xans-board-1002 \">\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li class=\"prev \"><strong>이전글</strong><a\r\n");
      out.write("												href=\"/board/free/read.html?no=27121&amp;board_no=1&amp;page=\"></a><a\r\n");
      out.write("												href=\"view.php?id=notice&amp;no=1118\">[마켓컬리] 수퍼세이브위크\r\n");
      out.write("													10/30 11시 ~ 10/31 11시 추가 적립금 응모자 대상 이벤트 당첨 안내</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/user/customerCenter/notice_detail.jsp(61,36) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.notice_date }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/user/customerCenter/notice_detail.jsp(61,36) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
