/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-17 12:25:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user.default_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div id=\"layerDSR\">\r\n");
      out.write("			<div class=\"bg_dim\"></div>\r\n");
      out.write("			<div class=\"in_layer\">\r\n");
      out.write("				<div class=\"inner_layer layer_star\">\r\n");
      out.write("					<strong class=\"dsr_result\">샛별배송 지역입니다.</strong>\r\n");
      out.write("					<div class=\"ani\">\r\n");
      out.write("						<img\r\n");
      out.write("							data-src=\"https://res.kurly.com/mobile/img/1908/img_delivery_kurly.png\"\r\n");
      out.write("							src=\"https://res.kurly.com/mobile/service/common/bg_1x1.png\"\r\n");
      out.write("							alt=\"샛별배송 이미지\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"dsr_desc default_cutoff_23_7\">\r\n");
      out.write("						<strong class=\"emph\">오늘 밤 11시 전</strong>까지 주문시<br> <strong\r\n");
      out.write("							class=\"emph\">다음날 아침 7시</strong> 이전 도착합니다!\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"dsr_desc early_cutoff_20_8\">\r\n");
      out.write("						<strong class=\"emph\">오늘 밤 8시 전</strong>까지 주문시<br> <strong\r\n");
      out.write("							class=\"emph\">다음날 아침 8시</strong> 이전 도착합니다!\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"inner_layer layer_normal\">\r\n");
      out.write("					<strong class=\"dsr_result\">택배배송 지역입니다.</strong>\r\n");
      out.write("					<div class=\"ani\">\r\n");
      out.write("						<img\r\n");
      out.write("							data-src=\"https://res.kurly.com/mobile/img/1908/img_delivery_car.png\"\r\n");
      out.write("							src=\"https://res.kurly.com/mobile/service/common/bg_1x1.png\"\r\n");
      out.write("							alt=\"택배배송 이미지\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"dsr_desc old_eight\">\r\n");
      out.write("						<strong class=\"emph\">밤 8시 전</strong>까지 주문시<br> <strong\r\n");
      out.write("							class=\"emph\">다음날</strong> 도착합니다!\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"dsr_desc new_ten\">\r\n");
      out.write("						<strong class=\"emph\">밤 10시 전</strong>까지 주문시<br> <strong\r\n");
      out.write("							class=\"emph\">다음날</strong> 도착합니다!\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"dsr_notice\">일요일은 배송 휴무로 토요일에는 주문 불가</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"inner_layer layer_none\">\r\n");
      out.write("					<strong class=\"dsr_result\">배송 불가 지역입니다.</strong>\r\n");
      out.write("					<div class=\"ani\">\r\n");
      out.write("						<img\r\n");
      out.write("							data-src=\"https://res.kurly.com/mobile/img/1908/img_delivery_none.png\"\r\n");
      out.write("							src=\"https://res.kurly.com/mobile/service/common/bg_1x1.png\"\r\n");
      out.write("							alt=\"배송불가 이미지\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"dsr_desc\">\r\n");
      out.write("						<strong class=\"emph\">도로명 주소</strong>로 검색하셨다면,<br> <strong\r\n");
      out.write("							class=\"emph\">지번 주소(구 주소)</strong>로 다시 시도해 주세요.\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"dsr_notice\">배송지역을 확장하도록 노력하겠습니다!</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"layer_btn1\">\r\n");
      out.write("					<button type=\"button\" class=\"btn_close\"\r\n");
      out.write("						onclick=\"$('#layerDSR').hide();$(this).parent().find('.inner_layer').hide();\">확인</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button type=\"button\" class=\"layer_close\"\r\n");
      out.write("					onclick=\"$('#layerDSR').hide();$(this).parent().find('.inner_layer').hide();\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"footer\">\r\n");
      out.write("			<div class=\"inner_footer\">\r\n");
      out.write("				<div class=\"footer_cc\">\r\n");
      out.write("					<h2 class=\"tit_cc\">고객행복센터</h2>\r\n");
      out.write("					<div class=\"cc_view cc_call\">\r\n");
      out.write("						<h3>\r\n");
      out.write("							<span class=\"tit\">1644-1107</span>\r\n");
      out.write("						</h3>\r\n");
      out.write("						<dl class=\"list\">\r\n");
      out.write("							<dt>365고객센터</dt>\r\n");
      out.write("							<dd>오전 7시 - 오후 7시</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"cc_view cc_kakao\">\r\n");
      out.write("						<h3>\r\n");
      out.write("							<a class=\"tit\" href=\"#none\">카카오톡 문의</a>\r\n");
      out.write("						</h3>\r\n");
      out.write("\r\n");
      out.write("						<dl class=\"list\">\r\n");
      out.write("							<dt>365고객센터</dt>\r\n");
      out.write("							<dd>오전 7시 - 오후 7시</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"cc_view cc_qna\">\r\n");
      out.write("						<h3>\r\n");
      out.write("							<a href=\"#none\"\r\n");
      out.write("								onclick=\"KurlyTrackerLink('/shop/mypage/mypage_qna_register.php?mode=add_qna', 'select_bottom_onebyone_button')\"\r\n");
      out.write("								class=\"tit\">1:1 문의</a>\r\n");
      out.write("						</h3>\r\n");
      out.write("						<dl class=\"list\">\r\n");
      out.write("							<dt>24시간 접수 가능</dt>\r\n");
      out.write("							<dd>고객센터 운영시간에 순차적으로 답변해드리겠습니다.</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"cc_view cc_bulkorder\">\r\n");
      out.write("						<h3>\r\n");
      out.write("							<a href=\"/shop/main/html.php?htmid=mypage/bulk_order.htm\"\r\n");
      out.write("								class=\"tit\">대량주문 문의</a>\r\n");
      out.write("						</h3>\r\n");
      out.write("						<p class=\"txt\">비회원의 경우 메일로 문의 바랍니다.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"company\">\r\n");
      out.write("					<ul class=\"list\">\r\n");
      out.write("						<li><a class=\"link\" href=\"/shop/introduce/about_kurly.php\">컬리소개</a></li>\r\n");
      out.write("						<li><a class=\"link\"\r\n");
      out.write("							href=\"https://www.youtube.com/embed/WEep7BcboMQ?rel=0&showinfo=0&wmode=opaque&enablejsapi=1\"\r\n");
      out.write("							onclick=\"window.open(this.href, 'pop', 'width=1330,height=660,scrollbars=yes');return false;\">컬리소개영상</a></li>\r\n");
      out.write("						<li><a class=\"link\"\r\n");
      out.write("							href=\"https://marketkurly.recruiter.co.kr/appsite/company/index\"\r\n");
      out.write("							target=\"_blank\">인재채용</a></li>\r\n");
      out.write("						<li><a class=\"link\" href=\"/shop/service/agreement.php\">이용약관</a></li>\r\n");
      out.write("						<li><a class=\"link emph\" href=\"/shop/service/private.php\">개인정보처리방침</a></li>\r\n");
      out.write("						<li><a class=\"link\" href=\"/shop/service/guide.php\">이용안내</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					법인명 (상호) : 주식회사 컬리 <span class=\"bar\">I</span> 사업자등록번호 :\r\n");
      out.write("					261-81-23567 <a\r\n");
      out.write("						href=\"http://www.ftc.go.kr/bizCommPop.do?wrkr_no=2618123567&apv_perm_no=\"\r\n");
      out.write("						target=\"_blank\" class=\"link\">사업자정보 확인</a> <br> 통신판매업 : 제\r\n");
      out.write("					2018-서울강남-01646 호 <span class=\"bar\">I</span> 개인정보보호책임자 : 이원준 <br>\r\n");
      out.write("					주소 : 서울특별시 강남구 테헤란로 133, 18층(역삼동) <span class=\"bar\">I</span> 대표이사 :\r\n");
      out.write("					김슬아 <br> 입점문의 : <a href=\"https://forms.gle/oKMAe1SaicqMX3SC9\"\r\n");
      out.write("						target=\"_blank\" class=\"link\">입점문의하기</a> <span class=\"bar\">I</span>\r\n");
      out.write("					제휴문의 : <a href=\"mailto:business@kurlycorp.com\" class=\"link\">business@kurlycorp.com</a>\r\n");
      out.write("					<br> 채용문의 : <a href=\"mailto:recruit@kurlycorp.com\"\r\n");
      out.write("						class=\"link\">recruit@kurlycorp.com</a> <br> 팩스: 070 - 7500 -\r\n");
      out.write("					6098 <span class=\"bar\">I</span> 이메일 : <a\r\n");
      out.write("						href=\"mailto:help@kurlycorp.com\" class=\"link\">help@kurlycorp.com</a>\r\n");
      out.write("					<br> 대량주문 문의 : <a href=\"mailto:kurlygift@kurlycorp.com\"\r\n");
      out.write("						class=\"link\">kurlygift@kurlycorp.com</a> <em class=\"copy\">&copy;\r\n");
      out.write("						KURLY CORP. ALL RIGHTS RESERVED</em>\r\n");
      out.write("					<ul class=\"list_sns\">\r\n");
      out.write("						<li><a href=\"https://instagram.com/marketkurly\"\r\n");
      out.write("							class=\"link_sns\" target=\"_blank\"><img\r\n");
      out.write("								src=\"https://res.kurly.com/pc/ico/1810/ico_instagram.png\"\r\n");
      out.write("								alt=\"마켓컬리 인스타그램 바로가기\"></a></li>\r\n");
      out.write("						<li><a href=\"https://www.facebook.com/marketkurly\"\r\n");
      out.write("							class=\"link_sns\" target=\"_blank\"><img\r\n");
      out.write("								src=\"https://res.kurly.com/pc/ico/1810/ico_fb.png\"\r\n");
      out.write("								alt=\"마켓컬리 페이스북 바로가기\"></a></li>\r\n");
      out.write("						<li><a href=\"http://blog.naver.com/marketkurly\"\r\n");
      out.write("							class=\"link_sns\" target=\"_blank\"><img\r\n");
      out.write("								src=\"https://res.kurly.com/pc/ico/1810/ico_blog.png\"\r\n");
      out.write("								alt=\"마켓컬리 네이버블로그 바로가기\"></a></li>\r\n");
      out.write("						<li><a href=\"https://m.post.naver.com/marketkurly\"\r\n");
      out.write("							class=\"link_sns\" target=\"_blank\"><img\r\n");
      out.write("								src=\"https://res.kurly.com/pc/ico/1810/ico_naverpost.png\"\r\n");
      out.write("								alt=\"마켓컬리 유튜브 바로가기\"></a></li>\r\n");
      out.write("						<li><a\r\n");
      out.write("							href=\"https://www.youtube.com/channel/UCfpdjL5pl-1qKT7Xp4UQzQg\"\r\n");
      out.write("							class=\"link_sns lst\" target=\"_blank\"><img\r\n");
      out.write("								src=\"https://res.kurly.com/pc/ico/1810/ico_youtube.png\"\r\n");
      out.write("								alt=\"마켓컬리 유튜브 바로가기\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footer_link\">\r\n");
      out.write("				<div class=\"authentication\">\r\n");
      out.write("					<a href=\"#none\"\r\n");
      out.write("						onclick=\"popup('https://res.kurly.com/pc/img/1909/img_isms.jpg',550,700);return false;\"\r\n");
      out.write("						class=\"mark\" target=\"_blank\"> <img\r\n");
      out.write("						src=\"https://res.kurly.com/pc/ico/2001/logo_isms.png\"\r\n");
      out.write("						alt=\"isms 로고\" class=\"logo\">\r\n");
      out.write("						<p class=\"txt\">\r\n");
      out.write("							[인증범위] 마켓컬리 쇼핑몰 서비스 개발 · 운영<br> [유효기간] 2019.04.01 ~\r\n");
      out.write("							2022.03.31\r\n");
      out.write("						</p>\r\n");
      out.write("					</a> <a href=\"#none\"\r\n");
      out.write("						onclick=\"popup('https://www.eprivacy.or.kr/front/certifiedSiteMark/certifiedSiteMarkPopup.do?certCmd=EP&certNum=2021-EP-R003',527,720);return false;\"\r\n");
      out.write("						class=\"mark\" target=\"_blank\"> <img\r\n");
      out.write("						src=\"https://res.kurly.com/pc/ico/2001/logo_eprivacyplus.png\"\r\n");
      out.write("						alt=\"eprivacy plus 로고\" class=\"logo\">\r\n");
      out.write("						<p class=\"txt\">\r\n");
      out.write("							개인정보보호 우수 웹사이트 ·<br> 개인정보처리시스템 인증 (ePRIVACY PLUS)\r\n");
      out.write("						</p>\r\n");
      out.write("					</a> <a href=\"#none\"\r\n");
      out.write("						onclick=\"popup('http://pgweb.uplus.co.kr/ms/escrow/s_escrowYn.do?mertid=go_thefarmers',460,550);return false;\"\r\n");
      out.write("						class=\"mark lguplus\" target=\"_blank\"> <img\r\n");
      out.write("						src=\"https://res.kurly.com/pc/service/main/2009/logo_payments.png\"\r\n");
      out.write("						alt=\"payments 로고\" class=\"logo\">\r\n");
      out.write("						<p class=\"txt\">\r\n");
      out.write("							고객님의 안전거래를 위해 현금 등으로 결제 시 저희 쇼핑몰에서 가입한<br> 토스 페이먼츠\r\n");
      out.write("							구매안전(에스크로) 서비스를 이용하실 수 있습니다.\r\n");
      out.write("						</p>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
