/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-06 03:30:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user.login_005fand_005fjoin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/secondk/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/marketKurlyty/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1632676361414L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/top.jsp", out, false);
      out.write("<!-- 기본 필요 meta, css는 include로 받아옴 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 여기부터 해당 페이지의 css 추가하면 됨-->\r\n");
      out.write("<link rel=\"styleSheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/style/ItemListStyle.css\">\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("function zip(){\r\n");
      out.write("	var myAddress;\r\n");
      out.write("	var myZipcode;\r\n");
      out.write("	new daum.Postcode({\r\n");
      out.write("		oncomplete:function(data){\r\n");
      out.write("			myAddress=data.address;\r\n");
      out.write("			myZipcode=data.zonecode;\r\n");
      out.write("			$(\"#zip\").val(myZipcode)\r\n");
      out.write("			$(\"#addr1\").val(myAddress);\r\n");
      out.write("			$(\".hid\").attr(\"class\",\".addressShow\");\r\n");
      out.write("		}\r\n");
      out.write("	}).open();\r\n");
      out.write("}\r\n");
      out.write("function validateEmail(email){\r\n");
      out.write("	var emailReg = /^(([^<>()\\[\\]\\.,;:\\s@\\\"]+(\\.[^<>()\\[\\]\\.,;:\\s@\\\"]+)*)|(\\\".+\\\"))@(([^<>()[\\]\\.,;:\\s@\\\"]+\\.)+[^<>()[\\]\\.,;:\\s@\\\"]{2,})$/i;\r\n");
      out.write("	return emailReg.test(email);\r\n");
      out.write("}\r\n");
      out.write("function formJoinSubmit(){\r\n");
      out.write("	//판별문\r\n");
      out.write("	var year = $(\"#birth_year\").val();\r\n");
      out.write("	var mon = $(\"#birth_month\").val();\r\n");
      out.write("	var day = $(\"#birth_day\").val();\r\n");
      out.write("	$(\"#totalbirth\").val(year+mon+day);\r\n");
      out.write("	\r\n");
      out.write("	if(document.frmMember.user_id.value==\"\"){\r\n");
      out.write("		alert(\"아이디를 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_id.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!KakaoJoin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("		if(document.frmMember.chk_id.value==\"불가능\"){\r\n");
      out.write("			alert(\"중복된 아이디는 사용할 수 없습니다.\");\r\n");
      out.write("			document.frmMember.user_id.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	if(document.frmMember.user_pw.value==\"\"){\r\n");
      out.write("		alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_pw.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.frmMember.user_pw_check.value==\"\"){\r\n");
      out.write("		alert(\"비밀번호 확인을 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_pw_check.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.frmMember.user_pw.value!=document.frmMember.user_pw_check.value){\r\n");
      out.write("		alert(\"비밀번호를 다시 확인해 주세요.\");\r\n");
      out.write("		document.frmMember.user_pw_check.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.frmMember.user_name.value==\"\"){\r\n");
      out.write("		alert(\"이름을 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_name.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.frmMember.user_email.value==\"\"){\r\n");
      out.write("		alert(\"이메일을 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_email.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(!validateEmail(document.frmMember.user_email.value)){\r\n");
      out.write("		alert(\"올바른 이메일을 입력해 주세요.\");\r\n");
      out.write("		document.regForm.email.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!KakaoJoin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("		if(document.frmMember.chk_email.value==\"불가능\"){\r\n");
      out.write("			alert(\"중복된 이메일은 사용할 수 없습니다.\");\r\n");
      out.write("			document.frmMember.user_email.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	if(document.frmMember.user_phone.value==\"\"){\r\n");
      out.write("		alert(\"전화번호를 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_phone.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	/* if(document.frmMember.okCerCheck.value==\"불가능\"){\r\n");
      out.write("		alert(\"문자 인증을 해주세요.\");\r\n");
      out.write("		return;\r\n");
      out.write("	} */\r\n");
      out.write("	if(document.frmMember.user_zipcode.value==\"\"){\r\n");
      out.write("		alert(\"주소를 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_zipcode.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.frmMember.user_birth.value==\"\"){\r\n");
      out.write("		alert(\"생년월일을 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_birth.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if($(\"input:checkbox[name=agree_allcheck]\").is(\":checked\")==false){\r\n");
      out.write("		alert(\"필수 약관에 동의해주세요.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	document.frmMember.submit();\r\n");
      out.write("}\r\n");
      out.write("function chkId(){\r\n");
      out.write("	var id = document.frmMember.user_id.value;\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"idCheck.do?user_id=\"+id,\r\n");
      out.write("		datatype:\"json\",\r\n");
      out.write("		success:function(res){\r\n");
      out.write("			const data = JSON.parse(res);\r\n");
      out.write("			alert(data.message);\r\n");
      out.write("			$(\"#posibleId\").val(data.usedId);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("function chkEmail(){\r\n");
      out.write("	var email = document.frmMember.user_email.value;\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"emailCheck.do?user_email=\"+email,\r\n");
      out.write("		datatype:\"json\",\r\n");
      out.write("		success:function(res){\r\n");
      out.write("			const data = JSON.parse(res);\r\n");
      out.write("			alert(data.message);\r\n");
      out.write("			$(\"#posibleEmail\").val(data.usedEmail);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("function smsResponse(){\r\n");
      out.write("	\r\n");
      out.write("	if(false){\r\n");
      out.write("		alert(\"문자 ㄱㄱ\");\r\n");
      out.write("		var phone = document.frmMember.user_phone.value;\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"smsCheck.do?user_phone=\"+phone,\r\n");
      out.write("			datatype:\"json\",\r\n");
      out.write("			success:function(res){\r\n");
      out.write("				const data = JSON.parse(res);\r\n");
      out.write("				$(\"#checkNum\").val(data.checkNum);\r\n");
      out.write("				$(\".phoneHid\").attr(\"class\",\"addressShow\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	$(\".phoneHid\").attr(\"class\",\"addressShow\");\r\n");
      out.write("}\r\n");
      out.write("function certCheck(){\r\n");
      out.write("	var smsCheck = $(\"#smsCheck\").val();\r\n");
      out.write("	var checkNum = $(\"#checkNum\").val();\r\n");
      out.write("	if(smsCheck==checkNum){\r\n");
      out.write("		alert(\"인증이 성공적으로 되었습니다.\");\r\n");
      out.write("		$(\"#okCerCheck\").val(\"가능\");\r\n");
      out.write("	}\r\n");
      out.write("	else{\r\n");
      out.write("		alert(\"인증에 실패했습니다. 다시 입력해주세요.\");\r\n");
      out.write("		$(\"#okCerCheck\").val(\"불가능\");\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	$(\"input[name=user_phone]\").on(\"keyup\", function() {\r\n");
      out.write("		$(this).val( $(this).val().replace(/[^0-9]/gi,\"\") );\r\n");
      out.write("	});\r\n");
      out.write("	$(\"input[name=user_id]\").on(\"keyup\",function(){\r\n");
      out.write("		$(this).val( $(this).val().replace(/[ㄱ-ㅎㅏ-ㅣ가-힣]/gi,\"\") );\r\n");
      out.write("	});\r\n");
      out.write("	$(\"input[name=user_pw]\").on(\"keyup\",function(){\r\n");
      out.write("		$(this).val( $(this).val().replace(/[^0-9a-z\\!\\@#$\\%\\^\\&\\*]/gi,\"\") );\r\n");
      out.write("	}).blur(function(){\r\n");
      out.write("		/* if(!(/[\\w\\!\\@#$\\%\\^\\&\\*]+[\\!\\@#$\\%\\^\\&\\*]/gi).test($(this).val())){\r\n");
      out.write("			alert(\"특수기호를 반드시 넣어야합니다.\");\r\n");
      out.write("		} */\r\n");
      out.write("		if(!(/[a-z]+/g).test($(this).val())){\r\n");
      out.write("			alert(\"영어와 숫자와 특수기호로 조합하여 만드시오.\");\r\n");
      out.write("		}\r\n");
      out.write("		if(!(/[A-Z]+/g).test($(this).val())){\r\n");
      out.write("			alert(\"영어대문자는 무조건 입력하세요.\");\r\n");
      out.write("		}\r\n");
      out.write("		if(!(/[0-9]*/gi).test($(this).val())){\r\n");
      out.write("			alert(\"영어와 숫자와 특수기호로 조합하여 만드시오.\");\r\n");
      out.write("		}\r\n");
      out.write("		if(!(/[\\!\\@#$\\%\\^\\&\\*]+/gi).test($(this).val())){\r\n");
      out.write("			alert(\"특수기호를 반드시 넣어야합니다.\");\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("function showPassword(){\r\n");
      out.write("	$(\"#password\").attr(\"type\",\"text\");\r\n");
      out.write("}\r\n");
      out.write("function hiddenPassword(){\r\n");
      out.write("	$(\"#password\").attr(\"type\",\"password\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".phoneHid{\r\n");
      out.write("	display:none;\r\n");
      out.write("}\r\n");
      out.write(".hid{\r\n");
      out.write("	display:none;\r\n");
      out.write("}\r\n");
      out.write(".addressShow{\r\n");
      out.write("	display:block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"main-index\" oncontextmenu=\"return false\"\r\n");
      out.write("	ondragstart=\"return false\" onselectstart=\"return !disableSelection\">\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrap\" class=\"\">\r\n");
      out.write("		<div id=\"pos_scroll\"></div>\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/header.jsp", out, false);
      out.write("<!-- header부분 -->\r\n");
      out.write("			<div id=\"main\">\r\n");
      out.write("				<div id=\"content\">\r\n");
      out.write("					<div class=\"tit_page\">\r\n");
      out.write("						<h2 class=\"tit\">회원가입</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/sidemenu.jsp", out, false);
      out.write("<!-- sidemenu부분 -->\r\n");
      out.write("					<div class=\"page_aticle\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"type_form member_join \">\r\n");
      out.write("							<form id=\"form\" name=\"frmMember\" method=\"post\" action=\"joinProc.do\" novalidate=\"\">\r\n");
      out.write("								<input type=\"hidden\" name=\"mode\" value=\"joinMember\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"check_mobile\" value=\"\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"auth_finish_code\" value=\"\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"rncheck\" value=\"\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"dupeinfo\" value=\"\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"pakey\" value=\"\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"foreigner\" value=\"\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"passwordSkin\" value=\"Y\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"private2\" value=\"\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"private3\" value=\"\"> <input\r\n");
      out.write("									type=\"hidden\" name=\"return_url\"\r\n");
      out.write("									value=\"https://www.kurly.com/shop/mypage/mypage_orderlist.php\">\r\n");
      out.write("								<p class=\"page_sub\">\r\n");
      out.write("									<span class=\"ico\">*</span>필수입력사항\r\n");
      out.write("								</p>\r\n");
      out.write("								<table class=\"tbl_comm\">\r\n");
      out.write("									<tbody>\r\n");
      out.write("										<tr class=\"fst\">\r\n");
      out.write("											<th>아이디<span class=\"ico\">*<span\r\n");
      out.write("													class=\"screen_out\">필수항목</span></span></th>\r\n");
      out.write("											<td>\r\n");
      out.write("												");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("												");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("												<p class=\"txt_guide square\">\r\n");
      out.write("													<span class=\"txt txt_case1\">6자 이상의 영문 혹은 영문과 숫자를 조합</span>\r\n");
      out.write("													<span class=\"txt txt_case2\">아이디 중복확인</span>\r\n");
      out.write("												</p></td>\r\n");
      out.write("										</tr>\r\n");
      out.write("\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th>비밀번호<span class=\"ico\">*<span\r\n");
      out.write("													class=\"screen_out\">필수항목</span></span></th>\r\n");
      out.write("											<td><input id=\"password\" type=\"password\" name=\"user_pw\" label=\"비밀번호\"\r\n");
      out.write("												maxlength=\"16\" class=\"reg_pw\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("												<input class=\"btn default\" type=\"button\" onmousedown=\"javascript:showPassword()\" \r\n");
      out.write("													onmouseup=\"javascript:hiddenPassword()\" value=\"암호보기\">\r\n");
      out.write("												<p class=\"txt_guide square\">\r\n");
      out.write("													<span class=\"txt txt_case1\">10자 이상 입력</span> <span\r\n");
      out.write("														class=\"txt txt_case2\">영문/숫자/특수문자(공백 제외)만 허용하며, 2개이상\r\n");
      out.write("														조합</span>\r\n");
      out.write("													<span class=\"txt txt_case3\">동일한 숫자 3개 이상 연속사용 불가</span>\r\n");
      out.write("												</p></td>\r\n");
      out.write("										</tr>\r\n");
      out.write("\r\n");
      out.write("										<tr class=\"member_pwd\">\r\n");
      out.write("											<th>비밀번호확인<span class=\"ico\">*<span\r\n");
      out.write("													class=\"screen_out\">필수항목</span></span></th>\r\n");
      out.write("											<td><input type=\"password\" name=\"user_pw_check\" maxlength=\"16\" class=\"confirm_pw\"\r\n");
      out.write("												placeholder=\"비밀번호를 한번 더 입력해주세요\">\r\n");
      out.write("												<p class=\"txt_guide square\">\r\n");
      out.write("													<span class=\"txt txt_case1\">동일한 비밀번호를 입력해주세요.</span>\r\n");
      out.write("												</p></td>\r\n");
      out.write("										</tr>\r\n");
      out.write("\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th>이름<span class=\"ico\">*<span class=\"screen_out\">필수항목</span></span></th>\r\n");
      out.write("											<td><input type=\"text\" name=\"user_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kakaoNickName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"이름을 입력해주세요\">\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th>이메일<span class=\"ico\">*<span\r\n");
      out.write("													class=\"screen_out\">필수항목</span></span></th>\r\n");
      out.write("											<td>\r\n");
      out.write("												");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("												");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr class=\"field_phone\">\r\n");
      out.write("											<th>휴대폰<span class=\"ico\">*<span\r\n");
      out.write("													class=\"screen_out\">필수항목</span></span></th>\r\n");
      out.write("											<td>\r\n");
      out.write("												<div class=\"phone_num\">\r\n");
      out.write("													<input type=\"text\" value=\"\" name=\"user_phone\" placeholder=\"숫자만 입력해주세요\" class=\"inp\">\r\n");
      out.write("													<button id=\"btn_cert\" class=\"btn default enabled\" onclick=\"smsResponse()\"\r\n");
      out.write("														type=\"button\">인증번호 받기</button>\r\n");
      out.write("												</div>\r\n");
      out.write("												<!-- <div id=\"codeNum\" class=\"code_num\">\r\n");
      out.write("													<input type=\"text\" name=\"auth_code\" id=\"auth_code\" value=\"\"\r\n");
      out.write("														size=\"6\" maxlength=\"6\" pattern=\"[0-9]*\" label=\"인증번호 확인\"\r\n");
      out.write("														disabled=\"\" class=\"inp_confirm\"\r\n");
      out.write("														oninput=\"if(value.length>6)value=value.slice(0,6);$(this).val($(this).val().replace(/[^0-9]/g,''));\">\r\n");
      out.write("\r\n");
      out.write("													<button id=\"btn_cert_confirm\" class=\"btn default disabled\"\r\n");
      out.write("														type=\"button\">인증번호 확인</button>\r\n");
      out.write("													<p id=\"countdown\" class=\"count_down\"></p>\r\n");
      out.write("												</div> -->\r\n");
      out.write("												<p class=\"txt_guide\">\r\n");
      out.write("													<span class=\"txt txt_case1\"></span>\r\n");
      out.write("												</p>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th></th>\r\n");
      out.write("											<td>\r\n");
      out.write("												<div class=\"phoneHid\">\r\n");
      out.write("													<input id=\"smsCheck\" type=\"text\" name=\"smsCheck\" size=\"6\" maxlength=\"6\" value=\"\" />\r\n");
      out.write("													<button id=\"btn_cert2\" class=\"btn default enabled\" onclick=\"certCheck()\"\r\n");
      out.write("														type=\"button\">인증번호 확인</button>\r\n");
      out.write("													<input type=\"hidden\" id=\"posiblePhone\"/>\r\n");
      out.write("													<input type=\"hidden\" id=\"checkNum\"/>\r\n");
      out.write("													<input type=\"hidden\" id=\"okCerCheck\" value=\"불가능\"/> \r\n");
      out.write("												</div>\r\n");
      out.write("											</td>\r\n");
      out.write("\r\n");
      out.write("										</tr>\r\n");
      out.write("										\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th>주소<span class=\"ico\">*<span class=\"screen_out\">필수항목</span></span></th>\r\n");
      out.write("												<td class=\"field_address\">\r\n");
      out.write("													<a href=\"#none\" id=\"addressSearch\" class=\"search\"\r\n");
      out.write("													onclick=\"zip()\"> <span\r\n");
      out.write("														id=\"addressNo\" class=\"address_no\" data-text=\"재검색\">주소\r\n");
      out.write("														검색</span>\r\n");
      out.write("												\r\n");
      out.write("													</a>\r\n");
      out.write("													<div id=\"selectAddressSub\">\r\n");
      out.write("														<input type=\"text\" name=\"address_sub\" id=\"address_sub\"\r\n");
      out.write("															value=\"\" class=\"byteTotext\" placeholder=\"나머지 주소를 입력해주세요\">\r\n");
      out.write("														<p id=\"delivery\"></p>\r\n");
      out.write("													</div>\r\n");
      out.write("													<p class=\"txt_guide\">\r\n");
      out.write("														<span class=\"txt txt_case1\">배송지에 따라 상품 정보가 달라질 수\r\n");
      out.write("															있습니다.</span>\r\n");
      out.write("													</p>\r\n");
      out.write("												</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th></th>\r\n");
      out.write("											<td>\r\n");
      out.write("												<div class=\"hid\">\r\n");
      out.write("													우편번호&nbsp;&nbsp;\r\n");
      out.write("													<input id=\"zip\" type=\"text\" name=\"user_zipcode\" maxlength=\"6\" value=\"\" />\r\n");
      out.write("												</div>\r\n");
      out.write("											</td>\r\n");
      out.write("\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th></th>\r\n");
      out.write("											<td>\r\n");
      out.write("												<div class=\"hid\">\r\n");
      out.write("													주소&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("													<input id=\"addr1\" type=\"text\" name=\"user_address1\" value=\"\" />\r\n");
      out.write("												</div>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th></th>\r\n");
      out.write("											<td>\r\n");
      out.write("												<div class=\"hid\">\r\n");
      out.write("													상세주소&nbsp;&nbsp;\r\n");
      out.write("													<input id=\"addr2\" type=\"text\" name=\"user_address2\" value=\"\" />\r\n");
      out.write("												</div>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("\r\n");
      out.write("										<tr class=\"select_sex\">\r\n");
      out.write("											<th>성별</th>\r\n");
      out.write("											<td>\r\n");
      out.write("												<label class=\"\">\r\n");
      out.write("													<input type=\"radio\" name=\"user_sex\" value=\"M\">\r\n");
      out.write("													<span class=\"ico\"></span>남자\r\n");
      out.write("												</label>\r\n");
      out.write("												<label class=\"\">\r\n");
      out.write("													<input type=\"radio\" name=\"user_sex\" value=\"W\">\r\n");
      out.write("													<span class=\"ico\"></span>여자\r\n");
      out.write("												</label>\r\n");
      out.write("												<label class=\"checked\">\r\n");
      out.write("													<input type=\"radio\" name=\"user_sex\" value=\"N\" checked=\"checked\">\r\n");
      out.write("													<span class=\"ico\"></span>선택안함\r\n");
      out.write("												</label></td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr class=\"birth field_birth\">\r\n");
      out.write("											<th>생년월일</th>\r\n");
      out.write("											<td>\r\n");
      out.write("												<div class=\"birth_day\">\r\n");
      out.write("													<input type=\"text\" name=\"birth_year\" id=\"birth_year\"\r\n");
      out.write("														pattern=\"[0-9]*\" value=\"\" label=\"생년월일\" size=\"4\"\r\n");
      out.write("														maxlength=\"4\" placeholder=\"YYYY\">\r\n");
      out.write("														<span class=\"bar\"></span>\r\n");
      out.write("														<input type=\"text\" name=\"birth[]\"\r\n");
      out.write("														id=\"birth_month\" pattern=\"[0-9]*\" value=\"\" label=\"생년월일\"\r\n");
      out.write("														size=\"2\" maxlength=\"2\" placeholder=\"MM\">\r\n");
      out.write("														<span class=\"bar\"></span>\r\n");
      out.write("														<input type=\"text\" name=\"birth[]\"\r\n");
      out.write("														id=\"birth_day\" pattern=\"[0-9]*\" value=\"\" label=\"생년월일\"\r\n");
      out.write("														size=\"2\" maxlength=\"2\" placeholder=\"DD\">\r\n");
      out.write("														\r\n");
      out.write("													<input id=\"totalbirth\" type=\"hidden\" name=\"user_birth\"/>\r\n");
      out.write("												</div>\r\n");
      out.write("												<p class=\"txt_guide\">\r\n");
      out.write("													<span class=\"txt bad\"></span>\r\n");
      out.write("												</p>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										\r\n");
      out.write("										<tr class=\"reg_agree\">\r\n");
      out.write("											<th>이용약관동의 <span class=\"ico\">*<span\r\n");
      out.write("													class=\"screen_out\">필수항목</span></span></th>\r\n");
      out.write("											<td>\r\n");
      out.write("												<div class=\"bg_dim\" style=\"display: none;\"></div>\r\n");
      out.write("												<div class=\"check\">\r\n");
      out.write("													<label class=\"check_agree label_all_check label_block\">\r\n");
      out.write("														<input type=\"checkbox\" name=\"agree_allcheck\"> <span\r\n");
      out.write("														class=\"ico\"></span>전체 동의합니다.\r\n");
      out.write("													</label>\r\n");
      out.write("													<p class=\"sub\">선택항목에 동의하지 않은 경우도 회원가입 및 일반적인 서비스를 이용할 수\r\n");
      out.write("														있습니다.</p>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"check_view\">\r\n");
      out.write("													<label class=\"check_agree label_block\"> <input type=\"checkbox\" value=\"\" name=\"agree\" required=\"\"\r\n");
      out.write("															label=\"이용약관\"> <span class=\"ico\"></span>이용약관\r\n");
      out.write("														동의 <span class=\"sub\">(필수)</span></label> <a href=\"#none\"\r\n");
      out.write("														class=\"link btn_link btn_agreement\">약관보기 </a>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layer layer_agreement\"\r\n");
      out.write("													style=\"display: none; margin-top: -299.5px;\">\r\n");
      out.write("													<div class=\"inner_layer\">\r\n");
      out.write("														<h4 class=\"tit_layer\">\r\n");
      out.write("															이용약관 <span class=\"sub\">(필수)</span>\r\n");
      out.write("														</h4>\r\n");
      out.write("														<div id=\"serviceView\" class=\"box_tbl\">\r\n");
      out.write("															<div class=\"box_type\">\r\n");
      out.write("																<h3 class=\"box_tit\">\r\n");
      out.write("																	<a class=\"btn_view\" href=\"#none\">총칙</a>\r\n");
      out.write("																</h3>\r\n");
      out.write("																<div class=\"box_view\">\r\n");
      out.write("																	<div class=\"txt_view\">\r\n");
      out.write("																		<!--1조-->\r\n");
      out.write("																		제1조(목적)<br> 이 약관은 주식회사 컬리 회사(전자상거래 사업자)가 운영하는\r\n");
      out.write("																		인터넷사이트 마켓컬리(이하 \"컬리\"라 한다)에서 제공하는 전자상거래 관련 서비스(이하 \"서비스\"라\r\n");
      out.write("																		한다)를 이용함에 있어 컬리와 이용자의 권리, 의무 및 책임사항을 규정함을 목적으로 합니다.<br>\r\n");
      out.write("																		*PC통신, 스마트폰 앱, 무선 등을 이용하는 전자상거래에 대해서도 그 성질에 반하지 않는 한\r\n");
      out.write("																		준용합니다. <br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--2조-->\r\n");
      out.write("																		제2조(정의)<br> ① \"컬리\"란 회사가 재화 또는 용역(이하 \"재화 등\"이라 함)을\r\n");
      out.write("																		이용자에게 제공하기 위하여 컴퓨터 등 정보통신설비를 이용하여 재화 등을 거래할 수 있도록 설정한\r\n");
      out.write("																		가상의 영업장을 말하며, 아울러 서비스를 운영하는 사업자의 의미로도 사용합니다.<br>\r\n");
      out.write("																		② \"이용자\"란 \"컬리\"에 접속하여 이 약관에 따라 \"컬리\"가 제공하는 서비스를 받는 회원 및\r\n");
      out.write("																		비회원을 말합니다.<br> ③ ‘회원’이라 함은 \"컬리\"에 회원등록을 한 자로서,\r\n");
      out.write("																		계속적으로 \"컬리\"가 제공하는 서비스를 이용할 수 있는 자를 말합니다.<br> ④\r\n");
      out.write("																		‘비회원’이라 함은 회원에 가입하지 않고 \"컬리\"가 제공하는 서비스를 이용하는 자를 말합니다.<br>\r\n");
      out.write("																		⑤ \"휴면회원\"이라 함은 \"컬리\"의 ‘회원’중 1년 이상 서비스 이용 기록이 없는 자를 말합니다.\r\n");
      out.write("																		휴면 회원은 \"컬리\"의 정책에 따라 서비스 이용이 제한 될 수 있으며, 다시 서비스를 이용하기\r\n");
      out.write("																		위하여는 거래 안전 등을 위하여 \"컬리\"가 정하는 본인확인 절차 등을 이행하여야 올바른 ‘회원’의\r\n");
      out.write("																		서비스를 이용할 수 있습니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--3조-->\r\n");
      out.write("																		제3조 (약관 등의 명시와 설명 및 개정) <br> ① \"컬리\"는 이 약관의 내용과 상호\r\n");
      out.write("																		및 대표자 성명, 영업소 소재지 주소(소비자의 불만을 처리할 수 있는 곳의 주소를 포함),\r\n");
      out.write("																		전화번호/모사전송번호/전자우편주소, 사업자등록번호, 통신판매업 신고번호, 개인정보 보호책임자 등을\r\n");
      out.write("																		이용자가 쉽게 알 수 있도록 컬리의 초기 서비스화면(전면)에 게시합니다. 다만, 약관의 내용은\r\n");
      out.write("																		이용자가 연결화면을 통하여 볼 수 있도록 할 수 있습니다.<br> ② \"컬리\"는 이용자가\r\n");
      out.write("																		약관에 동의하기에 앞서 약관에 정하여져 있는 내용 중 청약철회/배송책임/환불조건 등과 같은 중요한\r\n");
      out.write("																		내용을 이용자가 이해할 수 있도록 별도의 연결화면 또는 팝업화면 등을 제공하여 이용자의 확인을\r\n");
      out.write("																		구하여야 합니다.<br> ③ \"컬리\"는「전자상거래 등에서의 소비자보호에 관한 법률」,\r\n");
      out.write("																		「약관의 규제에 관한 법률」, 「전자문서 및 전자거래기본법」, 「전자금융거래법」, 「전자서명법」,\r\n");
      out.write("																		「개인정보보호법」, 「방문판매 등에 관한 법률」, 「소비자기본법」 등 관련 법을 위배하지 않는\r\n");
      out.write("																		범위에서 이 약관을 개정할 수 있습니다.<br> ④ \"컬리\"가 약관을 개정할 경우에는\r\n");
      out.write("																		적용일자 및 개정사유를 명시하여 현행약관과 함께 몰의 초기화면에 그 적용일자 7일 이전부터\r\n");
      out.write("																		적용일자 전일까지 공지합니다. 다만, 이용자에게 불리하게 약관내용을 변경하는 경우에는 최소한\r\n");
      out.write("																		30일 이상의 사전 유예기간을 두고 공지합니다. 이 경우 \"컬리\"는 개정 전 내용과 개정 후\r\n");
      out.write("																		내용을 명확하게 비교하여 이용자가 알기 쉽도록 표시합니다.<br> ⑤ \"컬리\"가 약관을\r\n");
      out.write("																		개정할 경우에는 그 개정약관은 그 적용일자 이후에 체결되는 계약에만 적용되고 그 이전에 이미\r\n");
      out.write("																		체결된 계약에 대해서는 개정 전의 약관조항이 그대로 적용됩니다. 다만 이미 계약을 체결한 이용자가\r\n");
      out.write("																		개정약관 조항의 적용을 받기를 원하는 뜻을 제4항에 의한 개정약관의 공지기간 내에 \"컬리\"에\r\n");
      out.write("																		송신하여 \"컬리\"의 동의를 받은 경우에는 개정약관 조항이 적용됩니다.<br> ⑥ 이\r\n");
      out.write("																		약관에서 정하지 아니한 사항과 이 약관의 해석에 관하여는 전자상거래 등에서의 소비자보호에 관한\r\n");
      out.write("																		법률, 약관의 규제 등에 관한 법률, 공정거래위원회가 정하는 전자상거래 등에서의 소비자 보호지침\r\n");
      out.write("																		및 관계법령 또는 상관례에 따릅니다.\r\n");
      out.write("																	</div>\r\n");
      out.write("																</div>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"box_type\">\r\n");
      out.write("																<h3 class=\"box_tit\">\r\n");
      out.write("																	<a class=\"btn_view\" href=\"#none\">회사의 서비스</a>\r\n");
      out.write("																</h3>\r\n");
      out.write("																<div class=\"box_view\">\r\n");
      out.write("																	<div class=\"txt_view\">\r\n");
      out.write("																		<!--4조-->\r\n");
      out.write("																		제4조(서비스의 제공 및 변경)<br> ① \"컬리\"는 다음과 같은 업무를 수행합니다.<br>\r\n");
      out.write("																		1. 재화 또는 용역에 대한 정보 제공 및 구매계약의 체결<br> 2. 구매계약이 체결된\r\n");
      out.write("																		재화 또는 용역의 배송<br> 3. 기타 \"컬리\"가 정하는 업무<br> ②\r\n");
      out.write("																		\"컬리\"는 재화 또는 용역의 품절 또는 기술적 사양의 변경 등의 경우에는 장차 체결되는 계약에\r\n");
      out.write("																		의해 제공할 재화 또는 용역의 내용을 변경할 수 있습니다. 이 경우에는 변경된 재화 또는 용역의\r\n");
      out.write("																		내용 및 제공일자를 명시하여 현재의 재화 또는 용역의 내용을 게시한 곳에 즉시 공지합니다.<br>\r\n");
      out.write("																		③ \"컬리\"가 제공하기로 이용자와 계약을 체결한 서비스의 내용을 재화등의 품절 또는 기술적 사양의\r\n");
      out.write("																		변경 등의 사유로 변경할 경우에는 그 사유를 이용자에게 통지 가능한 주소로 즉시 통지합니다.<br>\r\n");
      out.write("																		④ 전항의 경우 \"컬리\"는 이로 인하여 이용자가 입은 손해를 배상합니다. 다만, \"컬리\"가 고의\r\n");
      out.write("																		또는 과실이 없음을 입증하는 경우에는 그러하지 아니합니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--5조-->\r\n");
      out.write("																		제5조(서비스의 중단)<br> ① \"컬리\"는 컴퓨터 등 정보통신설비의 보수점검/교체 및\r\n");
      out.write("																		고장, 통신의 두절 등의 사유가 발생한 경우에는 서비스의 제공을 일시적으로 중단할 수 있습니다.<br>\r\n");
      out.write("																		② \"컬리\"는 제1항의 사유로 서비스의 제공이 일시적으로 중단됨으로 인하여 이용자 또는 제3자가\r\n");
      out.write("																		입은 손해에 대하여 배상합니다. 단, \"컬리\"가 고의 또는 과실이 없음을 입증하는 경우에는\r\n");
      out.write("																		그러하지 아니합니다.<br> ③ 사업종목의 전환, 사업의 포기, 업체 간의 통합 등의\r\n");
      out.write("																		이유로 서비스를 제공할 수 없게 되는 경우에는 \"컬리\"는 제8조에 정한 방법으로 이용자에게\r\n");
      out.write("																		통지하고 당초 \"컬리\"에서 제시한 조건에 따라 소비자에게 보상합니다. 다만, \"컬리\"가 보상기준\r\n");
      out.write("																		등을 고지하지 아니한 경우에는 이용자들의 마일리지 또는 적립금 등을 \"컬리\"에서 통용되는\r\n");
      out.write("																		통화가치에 상응하는 현물 또는 현금으로 이용자에게 지급합니다.\r\n");
      out.write("																	</div>\r\n");
      out.write("																</div>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"box_type\">\r\n");
      out.write("																<h3 class=\"box_tit\">\r\n");
      out.write("																	<a class=\"btn_view\" href=\"#none\">회원가입 계약</a>\r\n");
      out.write("																</h3>\r\n");
      out.write("																<div class=\"box_view\">\r\n");
      out.write("																	<div class=\"txt_view\">\r\n");
      out.write("																		<!--6조-->\r\n");
      out.write("																		제6조(회원가입) <br> ① 이용자는 \"컬리\"가 정한 가입 양식에 따라 회원정보를\r\n");
      out.write("																		기입한 후 이 약관에 동의한다는 의사표시를 함으로서 회원가입을 신청합니다.<br> ②\r\n");
      out.write("																		\"컬리\"는 제1항과 같이 회원으로 가입할 것을 신청한 이용자 중 다음 각 호에 해당하지 않는 한\r\n");
      out.write("																		회원으로 등록합니다.<br> 1. 가입신청자가 이 약관 제7조제3항에 의하여 이전에\r\n");
      out.write("																		회원자격을 상실한 적이 있는 경우, 다만 제7조제3항에 의한 회원자격 상실 후 3년이 경과한\r\n");
      out.write("																		자로서 \"컬리\"의 회원재가입 승낙을 얻은 경우에는 예외로 한다.<br> 2. 등록 내용에\r\n");
      out.write("																		허위, 기재누락, 오기가 있는 경우<br> 3. 기타 회원으로 등록하는 것이 \"컬리\"의\r\n");
      out.write("																		기술상 현저히 지장이 있다고 판단되는 경우<br> 4. 회원가입 및 전자상거래상의 계약에\r\n");
      out.write("																		관한 서비스는 만 14세 이상인자에 한함<br> ③ 회원가입계약의 성립 시기는 \"컬리\"의\r\n");
      out.write("																		승낙이 회원에게 도달한 시점으로 합니다.<br> ④ 회원은 회원가입 시 등록한 사항에\r\n");
      out.write("																		변경이 있는 경우, 상당한 기간 이내에 \"컬리\"에 대하여 회원정보 수정 등의 방법으로 그\r\n");
      out.write("																		변경사항을 알려야 합니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--7조-->\r\n");
      out.write("																		제7조(회원 탈퇴 및 자격 상실 등) <br> ① 회원은 \"컬리\"에 언제든지 탈퇴를\r\n");
      out.write("																		요청할 수 있으며 \"컬리\"는 회원의 요청을 받았을 경우 사이트를 통하여 \"컬리\"가 고지한 방법에\r\n");
      out.write("																		따라 신속하게 회원탈퇴를 처리합니다<br> ② 회원이 다음 각 호의 사유에 해당하는\r\n");
      out.write("																		경우, \"컬리\"는 회원자격을 제한 및 정지시킬 수 있습니다.<br> 1. 가입 신청 시에\r\n");
      out.write("																		타인의 정보 또는 허위의 정보를 입력하거나 가입 내용에 정보의 누락, 오기가 있는 경우<br>\r\n");
      out.write("																		2. \"컬리\"를 이용하여 구입한 재화 등의 대금, 기타 \"컬리\"이용에 관련하여 회원이 부담하는\r\n");
      out.write("																		채무를 기일에 지급하지 않는 경우<br> 3. 다른 사람의 \"컬리\" 이용을 방해하거나 그\r\n");
      out.write("																		정보를 도용하는 등 전자상거래 질서를 위협하는 경우<br> 4. \"컬리\"를 이용하여 법령\r\n");
      out.write("																		또는 이 약관이 금지하거나 공서양속에 반하는 행위를 하는 경우<br> 5. 기타 다음과\r\n");
      out.write("																		같은 행위 등으로 \"컬리\"의 건전한 운영을 해하거나 \"컬리\"의 업무를 방해하는 경우<br>\r\n");
      out.write("																		가. \"컬리\"의 운영과 관련하여 근거 없는 사실 또는 허위의 사실을 적시하거나 유포하여 \"컬리\"의\r\n");
      out.write("																		명예를 실추시키거나 \"컬리\"의 신뢰성을 해하는 경우<br> 나. \"컬리\"의 이용과정에서\r\n");
      out.write("																		직원에게 폭언, 협박 또는 음란한 언행, 이에 준하는 행동 등으로 \"컬리\"의 운영을 방해하는 경우<br>\r\n");
      out.write("																		다. \"컬리\"를 통하여 재화 등을 구매한 후 정당한 이유 없이 상습 또는 반복적으로 취소·반품하여\r\n");
      out.write("																		\"컬리\"의 업무를 방해하는 경우<br> 라. \"컬리\"를 통해 구입한 상품 또는 용역에\r\n");
      out.write("																		특별한 하자가 없는데도 불구하고 일부 사용 후 상습적인 취소·전부 또는 일부 반품, 이의 제기\r\n");
      out.write("																		등으로 회사의 업무를 방해하는 경우<br> 마. \"컬리\"가 본인 확인 절차를 실시할 경우\r\n");
      out.write("																		본인 확인이 되지 않거나 본인이 아님이 확인된 경우<br> 바. 이미 가입된 \"컬리\"의\r\n");
      out.write("																		회원의 개인정보(이름, 전화번호, 주소 등)와 동일한 경우<br> 사. 부정한 용도 또는\r\n");
      out.write("																		영리를 추구할 목적으로 서비스를 이용하는 경우<br> 아. 동일/유사한 아이디,\r\n");
      out.write("																		전화번호, 주소 등의 회원정보를 통하여 부정한 사용을 하는 것으로 의심되는 경우<br>\r\n");
      out.write("																		자. \"컬리\"로부터 서비스 제한, 회원 자격 정지 조치 등을 받은 회원이 그 조치기간 중에\r\n");
      out.write("																		이용계약을 임의해지하고 재이용신청을 하는 경우<br> 차. 무단으로 \"컬리\"의 재화,\r\n");
      out.write("																		용역, 정보를 수집하거나 외부에 제출, 게시, 이용하여 \"컬리\"의 저작권, 상표권 등 지식재산권을\r\n");
      out.write("																		침해하는 경우<br> 카. 이름, 주소, 전화번호 등 회원정보를 종합하여 실질적으로\r\n");
      out.write("																		동일인으로 인정되는 기존 회원이 다른 ID로 회원가입 또는 중복가입한 경우<br> ③\r\n");
      out.write("																		회원이 제2항에 해당하는 경우, \"컬리\"는 회원에게 제공한 혜택(적립금, 쿠폰 등)을 회수하거나\r\n");
      out.write("																		서비스 이용 제한(배송 취소 등)의 조치를 취할 수 있습니다.<br> ④ 재판매 목적\r\n");
      out.write("																		등으로 \"컬리\"에서 재화 등을 중복 구매하는 등 \"컬리\"의 거래질서를 방해하는 경우 \"컬리\"는\r\n");
      out.write("																		당해 회원의 회원자격을 상실시킬 수 있습니다.<br> ⑤ \"컬리\"가 회원 자격을\r\n");
      out.write("																		제한/정지 시킨 후, 동일한 행위가 2회 이상 반복되거나 30일 이내에 그 사유가 시정되지\r\n");
      out.write("																		아니하는 경우 \"컬리\"는 회원자격을 상실시킬 수 있습니다.<br> ⑥ \"컬리\"가\r\n");
      out.write("																		회원자격을 상실시키는 경우에는 회원등록을 말소합니다. 이 경우 회원에게 이를 통지하고, 회원등록\r\n");
      out.write("																		말소 전에 최소한 30일 이상의 기간을 정하여 소명할 기회를 부여합니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--8조-->\r\n");
      out.write("																		제8조(회원에 대한 통지)<br> ① \"컬리\"가 회원에 대한 통지를 하는 경우, 회원이\r\n");
      out.write("																		\"컬리\"와 미리 약정하여 지정한 전자우편(또는 우편), 문자, 전화, 팩스 등의 방법으로 할 수\r\n");
      out.write("																		있습니다.<br> ② \"컬리\"는 불특정다수 회원에 대한 통지의 경우 1주일이상 \"컬리\"\r\n");
      out.write("																		게시판에 게시함으로서 개별 통지에 갈음할 수 있습니다. 다만, 회원 본인의 거래와 관련하여 중대한\r\n");
      out.write("																		영향을 미치는 사항에 대하여는 개별통지를 합니다.\r\n");
      out.write("																	</div>\r\n");
      out.write("																</div>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"box_type\">\r\n");
      out.write("																<h3 class=\"box_tit\">\r\n");
      out.write("																	<a class=\"btn_view\" href=\"#none\">구매계약 및 대금 결제</a>\r\n");
      out.write("																</h3>\r\n");
      out.write("																<div class=\"box_view\">\r\n");
      out.write("																	<div class=\"txt_view\">\r\n");
      out.write("																		<!--9조-->\r\n");
      out.write("																		제9조(구매신청) <br> ① \"컬리\"이용자는 \"컬리\"상에서 다음 또는 이와 유사한\r\n");
      out.write("																		방법에 의하여 구매를 신청하며, \"컬리\"는 이용자가 구매신청을 함에 있어서 다음의 각 내용을 알기\r\n");
      out.write("																		쉽게 제공하여야 합니다.<br> 1. 재화 등의 검색 및 선택<br> 2. 받는\r\n");
      out.write("																		사람의 성명, 주소, 전화번호, 전자우편주소(또는 이동전화번호) 등의 입력<br> 3.\r\n");
      out.write("																		약관내용, 청약철회권이 제한되는 서비스, 배송료 등의 비용부담과 관련한 내용에 대한 확인<br>\r\n");
      out.write("																		4. 이 약관에 동의하고 위 3.호의 사항을 확인하거나 거부하는 표시(예, 마우스 클릭)<br>\r\n");
      out.write("																		5. 재화등의 구매신청 및 이에 관한 확인 또는 \"컬리\"의 확인에 대한 동의<br> 6.\r\n");
      out.write("																		결제방법의 선택<br> ② \"컬리\"가 제3자에게 구매자 개인정보를 제공/위탁할 필요가\r\n");
      out.write("																		있는 경우 실제 구매신청 시 구매자의 동의를 받아야 하며, 회원가입 시 미리 포괄적으로 동의를\r\n");
      out.write("																		받지 않습니다. 이 때 \"컬리\"는 제공되는 개인정보 항목, 제공받는 자, 제공받는 자의 개인정보\r\n");
      out.write("																		이용 목적 및 보유/이용 기간 등을 구매자에게 명시하여야 합니다. 다만 「개인정보보호법」\r\n");
      out.write("																		제26조에 의한 업무위탁에 따른 개인정보의 처리 제한 등 관련 법령에 달리 정함이 있는 경우에는\r\n");
      out.write("																		그에 따릅니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--10조-->\r\n");
      out.write("																		제10조 (계약의 성립)<br> ① \"컬리\"는 제9조와 같은 구매신청에 대하여 다음 각\r\n");
      out.write("																		호에 해당하면 승낙하지 않을 수 있습니다. 다만, 미성년자와 계약을 체결하는 경우에는 법정대리인의\r\n");
      out.write("																		동의를 얻지 못하면 미성년자 본인 또는 법정대리인이 계약을 취소할 수 있다는 내용을 고지하여야\r\n");
      out.write("																		합니다.<br> 1. 신청 내용에 허위, 기재누락, 오기가 있는 경우<br>\r\n");
      out.write("																		2. 미성년자가 담배, 주류 등 청소년보호법에서 금지하는 재화 및 용역을 구매하는 경우<br>\r\n");
      out.write("																		3. 기타 구매신청에 승낙하는 것이 \"컬리\" 기술상 현저히 지장이 있다고 판단하는 경우<br>\r\n");
      out.write("																		4. 구매신청 고객이 제7조에 따른 회원 자격이 제한·정지 또는 상실된 회원으로 확인되었을 경우<br>\r\n");
      out.write("																		② \"컬리\"의 승낙이 제14조제1항의 수신확인통지형태로 이용자에게 도달한 시점에 계약이 성립한\r\n");
      out.write("																		것으로 봅니다.<br> ③ \"컬리\"의 승낙의 의사표시에는 이용자의 구매 신청에 대한 확인\r\n");
      out.write("																		및 판매가능 여부, 구매신청의 정정 취소 등에 관한 정보 등을 포함하여야 합니다.<br>\r\n");
      out.write("																		<br>\r\n");
      out.write("\r\n");
      out.write("																		<!--11조-->\r\n");
      out.write("																		제11조(지급방법)<br> \"컬리\"에서 구매한 재화 또는 용역에 대한 대금지급방법은 다음\r\n");
      out.write("																		각 호의 방법중 가용한 방법으로 할 수 있습니다. 단, \"컬리\"는 이용자의 지급방법에 대하여 재화\r\n");
      out.write("																		등의 대금에 어떠한 명목의 수수료도 추가하여 징수할 수 없습니다.<br> ① 폰뱅킹,\r\n");
      out.write("																		인터넷뱅킹, 메일 뱅킹 등의 각종 계좌이체<br> ② 선불카드, 직불카드, 신용카드 등의\r\n");
      out.write("																		각종 카드 결제<br> ③ 온라인무통장입금<br> ④ 전자화폐에 의한 결제<br>\r\n");
      out.write("																		⑤ 수령 시 대금지급<br> ⑥ 마일리지 등 \"컬리\"가 지급한 적립금에 의한 결제<br>\r\n");
      out.write("																		⑦ \"컬리\"와 계약을 맺었거나 \"컬리\"가 인정한 상품권에 의한 결제<br> ⑧ 기타\r\n");
      out.write("																		전자적 지급 방법에 의한 대금 지급 등<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--12조-->\r\n");
      out.write("																		제12조(적립금)<br> ① \"컬리\"는 회원의 구매활동, 이벤트 참여 등에 따라 회원에게\r\n");
      out.write("																		일정한 적립금을 부여할 수 있습니다.<br> ② 회원은 적립금을 \"컬리\"에서 상품 등의\r\n");
      out.write("																		구매 시 결제 수단으로 사용할 수 있으며, \"컬리\"는 적립금의 적립기준, 사용방법, 사용기간 및\r\n");
      out.write("																		제한에 대한 사항을 사이트에 별도로 게시하거나 통지합니다. 적립금의 사용조건에 관한 사항은\r\n");
      out.write("																		\"컬리\"의 정책에 따라 달라질 수 있습니다.<br> ③ 적립금은 현금으로 환급될 수\r\n");
      out.write("																		없습니다.<br> ④ 회원은 적립금을 제3자에게 또는 다른 아이디로 양도할 수 없으며,\r\n");
      out.write("																		유상으로 거래하거나 현금으로 전환할 수 없습니다.<br> ⑤ \"컬리\"는 회원이 \"컬리\"가\r\n");
      out.write("																		승인하지 않은 방법 또는 허위 정보 제공 등의 부정한 방법으로 적립금을 획득하거나 부정한 목적이나\r\n");
      out.write("																		용도로 적립금을 사용하는 경우 적립금의 사용을 제한하거나 적립금을 사용한 구매신청을 취소하거나\r\n");
      out.write("																		회원 자격을 정지할 수 있습니다.<br> ⑥ 회원 탈퇴시 미사용한 적립금은 즉시\r\n");
      out.write("																		소멸되며, 탈퇴 후 재가입하더라도 소멸된 적립금은 복구되지 아니합니다.<br> ⑦ 회원이\r\n");
      out.write("																		구매 또는 이벤트 등으로 받은 적립금을 사용한 후 해당 적립 원인이 취소(반품)되는 경우 이를\r\n");
      out.write("																		\"컬리\"에 반환하여야 하며 적립금 잔여분이 있는 경우 자동으로 차감 되거나 또는 적립되는 즉시\r\n");
      out.write("																		해당 적립금이 충족 될 때까지 자동으로 차감됩니다.<br> ⑧ 적립금의 유효기간은 고지된\r\n");
      out.write("																		바에 따라 특정되며, 유효기간 내에 사용되지 않은 적립금은 해당 유효기간 만료 시 즉시\r\n");
      out.write("																		소멸됩니다.<br> ⑨ \"컬리\"의 적립금 정책은 제2조의 모든 ‘회원’에게 동일하게\r\n");
      out.write("																		적용됩니다. 단, 휴면회원의 경우 관계법령에 따라 고지, 처리 등이 제한 될 수 있습니다.<br>\r\n");
      out.write("																		<br>\r\n");
      out.write("\r\n");
      out.write("																		<!--13조-->\r\n");
      out.write("																		제13조(할인쿠폰)<br> ① 할인쿠폰은 회원에게 무상으로 발행되는 것으로 \"컬리\"는\r\n");
      out.write("																		회원이 할인쿠폰을 사이트에서 상품 구매 시 적용할 수 있도록 그 사용대상, 사용방법, 사용기간,\r\n");
      out.write("																		구매가 할인액 등을 정할 수 있습니다. 할인쿠폰의 종류 또는 내용은 \"컬리\"의 정책에 따라 달라질\r\n");
      out.write("																		수 있습니다.<br> ② \"컬리\"는 할인쿠폰의 사용대상, 사용방법, 사용기간, 할인금액\r\n");
      out.write("																		등을 사이트에 별도로 표시하거나 통지합니다.<br> ③ 할인쿠폰은 현금으로 환급될 수\r\n");
      out.write("																		없으며, 할인쿠폰의 사용기간이 만료되거나 구매 취소 시 또는 이용계약이 종료되면 소멸됩니다.<br>\r\n");
      out.write("																		④ 회원은 할인쿠폰을 제3자에게 또는 다른 아이디로 양도할 수 없으며, 유상으로 거래하거나\r\n");
      out.write("																		현금으로 전환할 수 없습니다.<br> ⑤ \"컬리\"는 회원이 \"컬리\"가 승인하지 않은\r\n");
      out.write("																		방법으로 할인쿠폰을 획득하거나 부정한 목적이나 용도로 할인쿠폰을 사용하는 경우 할인쿠폰의 사용을\r\n");
      out.write("																		제한하거나 할인쿠폰을 사용한 구매신청을 취소하거나 회원 자격을 정지할 수 있습니다.<br>\r\n");
      out.write("																		⑥ 회원 탈퇴 시 \"컬리\"로부터 발급받은 할인쿠폰 중 미사용한 할인쿠폰은 즉시 소멸되며, 탈퇴 후\r\n");
      out.write("																		재가입하더라도 소멸된 할인쿠폰은 복구되지 아니합니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--14조-->\r\n");
      out.write("																		제14조(수신확인통지/구매신청 변경 및 취소)<br> ① \"컬리\"는 이용자의 구매신청이\r\n");
      out.write("																		있는 경우 이용자에게 수신확인통지를 합니다.<br> ② 수신확인통지를 받은 이용자는\r\n");
      out.write("																		의사표시의 불일치 등이 있는 경우에는 수신확인통지를 받은 후 즉시 구매신청 변경 및 취소를 요청할\r\n");
      out.write("																		수 있고 \"컬리\"는 배송 전에 이용자의 요청이 있는 경우에는 지체 없이 그 요청에 따라 처리하여야\r\n");
      out.write("																		합니다. 다만 이미 대금을 지불한 경우에는 제17조의 청약철회 등에 관한 규정에 따릅니다.<br>\r\n");
      out.write("																		<br>\r\n");
      out.write("\r\n");
      out.write("																		<!--15조-->\r\n");
      out.write("																		제15조(재화 등의 공급)<br> ① \"컬리\"는 이용자와 재화 등의 공급시기에 관하여\r\n");
      out.write("																		별도의 약정이 없는 이상, 이용자가 청약을 한 날부터 7일 이내에 재화 등을 배송할 수 있도록\r\n");
      out.write("																		주문제작, 포장 등 기타의 필요한 조치를 취합니다. 다만, \"컬리\"가 이미 재화 등의 대금의 전부\r\n");
      out.write("																		또는 일부를 받은 경우에는 대금의 전부 또는 일부를 받은 날부터 3영업일 이내에 조치를 취합니다.\r\n");
      out.write("																		이때 \"컬리\"는 이용자가 재화 등의 공급 절차 및 진행 사항을 확인할 수 있도록 적절한 조치를\r\n");
      out.write("																		합니다.<br> ② \"컬리\"는 이용자가 구매한 재화에 대해 배송수단, 수단별 배송비용\r\n");
      out.write("																		부담자, 수단별 배송기간 등을 명시합니다. 만약 \"컬리\"가 약정 배송기간을 초과한 경우에는 그로\r\n");
      out.write("																		인한 이용자의 손해를 배상하여야 합니다. 다만 \"컬리\"가 고의/과실이 없음을 입증한 경우에는\r\n");
      out.write("																		그러하지 아니합니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--16조-->\r\n");
      out.write("																		제16조(환급)<br> \"컬리\"는 이용자가 구매신청한 재화 등이 품절 등의 사유로 인도\r\n");
      out.write("																		또는 제공을 할 수 없을 때에는 지체 없이 그 사유를 이용자에게 통지하고 사전에 재화 등의 대금을\r\n");
      out.write("																		받은 경우에는 대금을 받은 날부터 3영업일 이내에 환급하거나 환급에 필요한 조치를 취합니다.<br>\r\n");
      out.write("																		<br>\r\n");
      out.write("\r\n");
      out.write("																		<!--17조-->\r\n");
      out.write("																		제17조(청약철회 등)<br> ① \"컬리\"와 재화등의 구매에 관한 계약을 체결한 이용자는\r\n");
      out.write("																		「전자상거래 등에서의 소비자보호에 관한 법률」 제13조 제2항에 따른 계약내용에 관한 서면을 받은\r\n");
      out.write("																		날(그 서면을 받은 때보다 재화 등의 공급이 늦게 이루어진 경우에는 재화 등을 공급받거나 재화\r\n");
      out.write("																		등의 공급이 시작된 날을 말합니다)부터 7일 이내에는 청약의 철회를 할 수 있습니다. 다만,\r\n");
      out.write("																		청약철회에 관하여 「전자상거래 등에서의 소비자보호에 관한 법률」에 달리 정함이 있는 경우에는 동\r\n");
      out.write("																		법 규정에 따릅니다.<br> ② 이용자는 재화 등을 배송 받은 경우 다음 각 호의 1에\r\n");
      out.write("																		해당하는 경우에는 반품 및 교환을 할 수 없습니다.<br> 1. 이용자에게 책임 있는\r\n");
      out.write("																		사유로 재화 등이 멸실 또는 훼손된 경우(다만, 재화 등의 내용을 확인하기 위하여 포장 등을\r\n");
      out.write("																		훼손한 경우에는 청약철회를 할 수 있습니다)<br> 2. 이용자의 사용 또는 일부 소비에\r\n");
      out.write("																		의하여 재화 등의 가치가 현저히 감소한 경우<br> 3. 시간의 경과에 의하여 재판매가\r\n");
      out.write("																		곤란할 정도로 재화등의 가치가 현저히 감소한 경우<br> 4. 같은 성능을 지닌 재화\r\n");
      out.write("																		등으로 복제가 가능한 경우 그 원본인 재화 등의 포장을 훼손한 경우<br> ③\r\n");
      out.write("																		제2항제2호 내지 제4호의 경우에 \"컬리\"가 사전에 청약철회 등이 제한되는 사실을 소비자가 쉽게\r\n");
      out.write("																		알 수 있는 곳에 명기하거나 시용상품을 제공하는 등의 조치를 하지 않았다면 이용자의 청약철회 등이\r\n");
      out.write("																		제한되지 않습니다.<br> ④ 이용자는 제1항 및 제2항의 규정에 불구하고 재화 등의\r\n");
      out.write("																		내용이 표시/광고 내용과 다르거나 계약내용과 다르게 이행된 때에는 당해 재화 등을 공급받은 날부터\r\n");
      out.write("																		3월 이내, 그 사실을 안 날 또는 알 수 있었던 날부터 30일 이내에 청약철회 등을 할 수\r\n");
      out.write("																		있습니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--18조-->\r\n");
      out.write("																		제18조(청약철회 등의 효과)<br> ① \"컬리\"는 이용자로부터 재화 등을 반환받은 경우\r\n");
      out.write("																		3영업일 이내에 이미 지급받은 재화 등의 대금을 환급합니다. 이 경우 \"컬리\"가 이용자에게\r\n");
      out.write("																		재화등의 환급을 지연한때에는 그 지연기간에 대하여 「전자상거래 등에서의 소비자보호에 관한 법률\r\n");
      out.write("																		시행령」제21조의2에서 정하는 지연이자율을 곱하여 산정한 지연이자를 지급합니다.<br>\r\n");
      out.write("																		② \"컬리\"는 위 대금을 환급함에 있어서 이용자가 신용카드 또는 전자화폐 등의 결제수단으로 재화\r\n");
      out.write("																		등의 대금을 지급한 때에는 지체 없이 당해 결제수단을 제공한 사업자로 하여금 재화 등의 대금의\r\n");
      out.write("																		청구를 정지 또는 취소하도록 요청합니다.<br> ③ 청약철회 등의 경우 공급받은 재화\r\n");
      out.write("																		등의 반환에 필요한 비용은 이용자가 부담합니다. \"컬리\"는 이용자에게 청약철회 등을 이유로 위약금\r\n");
      out.write("																		또는 손해배상을 청구하지 않습니다. 다만 재화 등의 내용이 표시/광고 내용과 다르거나 계약내용과\r\n");
      out.write("																		다르게 이행되어 청약철회 등을 하는 경우 재화 등의 반환에 필요한 비용은 \"컬리\"가 부담합니다.<br>\r\n");
      out.write("																		④ 이용자가 재화 등을 제공받을 때 발송비를 부담한 경우에 \"컬리\"는 청약철회 시 그 비용을 누가\r\n");
      out.write("																		부담하는지를 이용자가 알기 쉽도록 명확하게 표시합니다.\r\n");
      out.write("																	</div>\r\n");
      out.write("																</div>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"box_type\">\r\n");
      out.write("																<h3 class=\"box_tit\">\r\n");
      out.write("																	<a class=\"btn_view\" href=\"#none\">계약 당사자의 의무</a>\r\n");
      out.write("																</h3>\r\n");
      out.write("																<div class=\"box_view\">\r\n");
      out.write("																	<div class=\"txt_view\">\r\n");
      out.write("																		<!--19조-->\r\n");
      out.write("																		제19조(개인정보보호)<br> ① \"컬리\"는 이용자의 개인정보 수집시 서비스제공을 위하여\r\n");
      out.write("																		필요한 범위에서 최소한의 개인정보를 수집합니다.<br> ② \"컬리\"는 회원가입시\r\n");
      out.write("																		구매계약이행에 필요한 정보를 미리 수집하지 않습니다. 다만, 관련 법령상 의무이행을 위하여\r\n");
      out.write("																		구매계약 이전에 본인확인이 필요한 경우로서 최소한의 특정 개인정보를 수집하는 경우에는 그러하지\r\n");
      out.write("																		아니합니다.<br> ③ \"컬리\"는 이용자의 개인정보를 수집/이용하는 때에는 당해\r\n");
      out.write("																		이용자에게 그 목적을 고지하고 동의를 받습니다.<br> ④ \"컬리\"는 수집된 개인정보를\r\n");
      out.write("																		목적외의 용도로 이용할 수 없으며, 새로운 이용목적이 발생한 경우 또는 제3자에게 제공하는\r\n");
      out.write("																		경우에는 이용/제공단계에서 당해 이용자에게 그 목적을 고지하고 동의를 받습니다. 다만, 관련\r\n");
      out.write("																		법령에 달리 정함이 있는 경우에는 예외로 합니다.<br> ⑤ \"컬리\"가 제2항과 제3항에\r\n");
      out.write("																		의해 이용자의 동의를 받아야 하는 경우에는 개인정보 보호책임자의 신원(소속, 성명 및 전화번호,\r\n");
      out.write("																		기타 연락처), 정보의 수집목적 및 이용목적, 제3자에 대한 정보제공 관련사항(제공받은자,\r\n");
      out.write("																		제공목적 및 제공할 정보의 내용) 등 「개인정보보호법」 제39조의3이 규정한 사항을 미리\r\n");
      out.write("																		명시하거나 고지해야 하며 이용자는 언제든지 이 동의를 철회할 수 있습니다.<br> ⑥\r\n");
      out.write("																		이용자는 언제든지 \"컬리\"가 가지고 있는 자신의 개인정보에 대해 열람 및 오류정정을 요구할 수\r\n");
      out.write("																		있으며 \"컬리\"는 이에 대해 지체 없이 필요한 조치를 취할 의무를 집니다. 이용자가 오류의 정정을\r\n");
      out.write("																		요구한 경우에는 \"컬리\"는 그 오류를 정정할 때까지 당해 개인정보를 이용하지 않습니다.<br>\r\n");
      out.write("																		⑦ \"컬리\"는 개인정보 보호를 위하여 이용자의 개인정보를 취급하는 자를 최소한으로 제한하여야 하며\r\n");
      out.write("																		신용카드, 은행계좌 등을 포함한 이용자의 개인정보의 분실, 도난, 유출, 동의 없는 제3자 제공,\r\n");
      out.write("																		변조 등으로 인한 이용자의 손해에 대하여 모든 책임을 집니다.<br> ⑧ \"컬리\" 또는\r\n");
      out.write("																		그로부터 개인정보를 제공받은 제3자는 개인정보의 수집목적 또는 제공받은 목적을 달성한 때에는 당해\r\n");
      out.write("																		개인정보를 지체 없이 파기합니다.<br> ⑨ \"컬리\"는 개인정보의 수집/이용/제공에 관한\r\n");
      out.write("																		동의란을 미리 선택한 것으로 설정해두지 않습니다. 또한 개인정보의 수집/이용/제공에 관한 이용자의\r\n");
      out.write("																		동의거절시 제한되는 서비스를 구체적으로 명시하고, 필수수집항목이 아닌 개인정보의 수집/이용/제공에\r\n");
      out.write("																		관한 이용자의 동의 거절을 이유로 회원가입 등 서비스 제공을 제한하거나 거절하지 않습니다.<br>\r\n");
      out.write("																		<br>\r\n");
      out.write("\r\n");
      out.write("																		<!--20조-->\r\n");
      out.write("																		제20조(\"컬리\"의 의무)<br> ① \"컬리\"는 법령과 이 약관이 금지하거나 공서양속에\r\n");
      out.write("																		반하는 행위를 하지 않으며 이 약관이 정하는 바에 따라 지속적이고, 안정적으로 재화/용역을\r\n");
      out.write("																		제공하는데 최선을 다하여야 합니다.<br> ② \"컬리\"는 이용자가 안전하게 인터넷\r\n");
      out.write("																		서비스를 이용할 수 있도록 이용자의 개인정보(신용정보 포함)보호를 위한 보안 시스템을 갖추어야\r\n");
      out.write("																		합니다.<br> ③ \"컬리\"가 상품이나 용역에 대하여 「표시·광고의 공정화에 관한 법률」\r\n");
      out.write("																		제3조 소정의 부당한 표시/광고행위를 함으로써 이용자가 손해를 입은 때에는 이를 배상할 책임을\r\n");
      out.write("																		집니다.<br> ④ \"컬리\"는 이용자가 원하지 않는 영리목적의 광고성 전자우편을 발송하지\r\n");
      out.write("																		않습니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--21조-->\r\n");
      out.write("																		제21조(회원의 ID 및 비밀번호에 대한 의무)<br> ① 제19조의 경우를 제외한\r\n");
      out.write("																		ID와 비밀번호에 관한 관리책임은 회원에게 있습니다.<br> ② 회원은 자신의 ID 및\r\n");
      out.write("																		비밀번호를 제3자에게 이용하게 해서는 안됩니다.<br> ③ 회원이 자신의 ID 및\r\n");
      out.write("																		비밀번호를 도난당하거나 제3자가 사용하고 있음을 인지한 경우에는 바로 \"컬리\"에 통보하고\r\n");
      out.write("																		\"컬리\"의 안내가 있는 경우에는 그에 따라야 합니다.\r\n");
      out.write("																	</div>\r\n");
      out.write("																</div>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"box_type\">\r\n");
      out.write("																<h3 class=\"box_tit\">\r\n");
      out.write("																	<a class=\"btn_view\" href=\"#none\">기타</a>\r\n");
      out.write("																</h3>\r\n");
      out.write("																<div class=\"box_view\">\r\n");
      out.write("																	<div class=\"txt_view\">\r\n");
      out.write("																		<!--22조-->\r\n");
      out.write("																		제22조(이용자의 의무)<br> 이용자는 다음 행위를 하여서는 안 됩니다.<br>\r\n");
      out.write("																		1. 신청 또는 변경시 허위 내용의 등록<br> 2. 타인의 정보 도용<br>\r\n");
      out.write("																		3. \"컬리\"에 게시된 정보의 변경<br> 4. \"컬리\"가 정한 정보 이외의 정보(컴퓨터\r\n");
      out.write("																		프로그램 등) 등의 송신 또는 게시<br> 5. \"컬리\" 기타 제3자의 저작권 등\r\n");
      out.write("																		지식재산권에 대한 침해<br> 6. \"컬리\" 기타 제3자의 명예를 손상시키거나 업무를\r\n");
      out.write("																		방해하는 행위<br> 7. 외설 또는 폭력적인 메시지, 화상, 음성, 기타 공서양속에\r\n");
      out.write("																		반하는 정보를 몰에 공개 또는 게시하는 행위<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--23조-->\r\n");
      out.write("																		제23조(지식재산권의 귀속 및 이용제한)<br> ① \"컬리\"가 작성한 저작물에 대한\r\n");
      out.write("																		저작권 기타 지식재산권은 \"컬리\"에 귀속합니다.<br> ② 이용자는 \"컬리\"를\r\n");
      out.write("																		이용함으로써 얻은 정보 중 \"컬리\"에게 지식재산권이 귀속된 정보를 \"컬리\"의 사전 승낙 없이\r\n");
      out.write("																		복제, 송신, 출판, 배포, 방송 기타 방법에 의하여 영리목적으로 이용하거나 제3자에게 이용하게\r\n");
      out.write("																		하여서는 안됩니다.<br> ③ \"컬리\"는 약정에 따라 이용자에게 귀속된 지식재산권을\r\n");
      out.write("																		사용하는 경우 당해 이용자에게 통보하여야 합니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--24조-->\r\n");
      out.write("																		제24조(면책조항)<br> ① \"컬리\"는 천재지변 또는 이에 준하는 불가항력으로 인하여\r\n");
      out.write("																		서비스를 제공할 수 없는 경우에는 서비스 제공에 관한 책임이 면제됩니다.<br> ②\r\n");
      out.write("																		\"컬리\"는 회원의 귀책사유로 인한 서비스 이용의 장애에 대하여 책임을 지지 않습니다.<br>\r\n");
      out.write("																		③ \"컬리\"는 회원이 서비스를 이용하여 기대하는 수익을 상실한 것에 대하여 책임을 지지 않으며,\r\n");
      out.write("																		그 밖의 서비스를 통하여 얻은 자료로 인한 손해에 관하여 책임을 지지 않습니다.<br>\r\n");
      out.write("																		④ \"컬리\"는 회원이 게재한 정보, 자료, 사실의 신뢰도, 정확성 등 내용에 관해서는 책임을 지지\r\n");
      out.write("																		않습니다.<br> ⑤ \"컬리\"는 회원 간 또는 회원과 제3자 상호간에 서비스를 매개로\r\n");
      out.write("																		하여 거래 등을 한 경우에는 책임을 지지 않습니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--25조-->\r\n");
      out.write("																		제25조(분쟁해결)<br> ① \"컬리\"는 이용자가 제기하는 정당한 의견이나 불만을\r\n");
      out.write("																		반영하고 그 피해를 보상처리하기 위하여 피해보상처리기구를 설치/운영합니다.<br> ②\r\n");
      out.write("																		\"컬리\"는 이용자로부터 제출되는 불만사항 및 의견은 우선적으로 그 사항을 처리합니다. 다만,\r\n");
      out.write("																		신속한 처리가 곤란한 경우에는 이용자에게 그 사유와 처리일정을 즉시 통보해 드립니다.<br>\r\n");
      out.write("																		③ \"컬리\"와 이용자 간에 발생한 전자상거래 분쟁과 관련하여 이용자의 피해구제신청이 있는 경우에는\r\n");
      out.write("																		공정거래위원회 또는 시/도지사가 의뢰하는 분쟁조정기관의 조정에 따를 수 있습니다.<br>\r\n");
      out.write("																		<br>\r\n");
      out.write("\r\n");
      out.write("																		<!--26조-->\r\n");
      out.write("																		제26조(재판권 및 준거법)<br> ① \"컬리\"와 이용자 간에 발생한 전자상거래 분쟁에\r\n");
      out.write("																		관한 소송은 제소 당시의 이용자의 주소에 의하고, 주소가 없는 경우에는 거소를 관할하는 지방법원의\r\n");
      out.write("																		전속관할로 합니다. 다만, 제소 당시 이용자의 주소 또는 거소가 분명하지 않거나 외국 거주자의\r\n");
      out.write("																		경우에는 민사소송법상의 관할법원에 제기합니다.<br> ② \"컬리\"와 이용자 간에 제기된\r\n");
      out.write("																		전자상거래 소송에는 한국법을 적용합니다.<br> <br>\r\n");
      out.write("\r\n");
      out.write("																		<!--부칙-->\r\n");
      out.write("																		* 부칙<br> 1. 이 약관은 2021년 06월 22일부터 시행됩니다.<br>\r\n");
      out.write("																		2. 2020년 3월 11일부터 시행되던 종전의 약관은 이 약관으로 대체됩니다.\r\n");
      out.write("																	</div>\r\n");
      out.write("																</div>\r\n");
      out.write("															</div>\r\n");
      out.write("														</div>\r\n");
      out.write("\r\n");
      out.write("														<button type=\"button\" class=\"btn_ok\">확인</button>\r\n");
      out.write("														<button type=\"button\" class=\"btn_close\">\r\n");
      out.write("															<span class=\"screen_out\">레이어 닫기</span>\r\n");
      out.write("														</button>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"check_view\">\r\n");
      out.write("													<label class=\"check_agree label_block\"> <inputtype\r\n");
      out.write("															=\"checkbox\" id=\"private1\" name=\"private1\" value=\"\"\r\n");
      out.write("															required=\"\" label=\"개인정보 수집·이용\"> <span\r\n");
      out.write("															class=\"ico\"></span>개인정보수집·이용 동의 <span class=\"sub\">(필수)</span></label>\r\n");
      out.write("													<a href=\"#none\" class=\"link btn_link btn_essential\">약관보기</a>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layer layer_essential\" style=\"display: none;\">\r\n");
      out.write("													<div class=\"inner_layer\">\r\n");
      out.write("														<div class=\"in_layer\">\r\n");
      out.write("															<h4 class=\"tit_layer\">\r\n");
      out.write("																개인정보 수집·이용 동의 <span class=\"sub\">(필수)</span>\r\n");
      out.write("															</h4>\r\n");
      out.write("															<div class=\"box_tbl\">\r\n");
      out.write("																<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("																	<caption class=\"screen_out\">개인정보 수집·이용 동의(필수)</caption>\r\n");
      out.write("																	<thead>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<th scope=\"row\" class=\"tit1\">수집 목적</th>\r\n");
      out.write("																			<th scope=\"row\" class=\"tit2\">수집 항목</th>\r\n");
      out.write("																			<th scope=\"row\" class=\"tit3\">보유 기간</th>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																	</thead>\r\n");
      out.write("																	<tbody>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<td>이용자 식별 및 본인여부</td>\r\n");
      out.write("																			<td rowspan=\"4\">이름, 아이디, 비밀번호, 휴대폰번호, 이메일, 주소</td>\r\n");
      out.write("																			<td rowspan=\"4\" class=\"emph\">회원 탈퇴 <br>즉시파기\r\n");
      out.write("																				<br> <br> 부정이용 방지를 위하여 30일 동안 보관 (아이디,휴대폰\r\n");
      out.write("																				번호) 후 파기\r\n");
      out.write("																			</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<td>거점 기반 서비스 제공</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<td>계약 이행 및 약관변경 등의 고지를 위한 연락, 본인의사 확인 및 민원 등의\r\n");
      out.write("																				고객 고충 처리</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<td>부정 이용 방지, 비인가 사용방지 및 서비스 제공 및 계약의 이행</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<td>서비스방문 및 이용기록 분석, 부정이용 방지 등을 위한 기록 관리</td>\r\n");
      out.write("																			<td>서비스 이용기록, IP주소, 쿠키, MAC 주소, 모바일 기기정보(광고식별자,\r\n");
      out.write("																				OS/ 앱 버전)</td>\r\n");
      out.write("																			<td class=\"emph\">회원 탈퇴 즉시 또는 이용 목적 달성 즉시 파기</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																	</tbody>\r\n");
      out.write("																</table>\r\n");
      out.write("															</div>\r\n");
      out.write("															<p class=\"txt_service\">서비스 제공을 위해서 필요한 최소한의 개인정보입니다.\r\n");
      out.write("																동의를 해 주셔야 서비스를 이용하실 수 있으며, 동의하지 않으실 경우 서비스에 제한이 있을 수\r\n");
      out.write("																있습니다.</p>\r\n");
      out.write("														</div>\r\n");
      out.write("														<button type=\"button\" class=\"btn_ok\">\r\n");
      out.write("															<span class=\"txt_type\">확인</span>\r\n");
      out.write("														</button>\r\n");
      out.write("														<button type=\"button\" class=\"btn_close\">\r\n");
      out.write("															<span class=\"screen_out\">레이어 닫기</span>\r\n");
      out.write("														</button>\r\n");
      out.write("													</div>\r\n");
      out.write("													<button type=\"button\" class=\"btn_close\">\r\n");
      out.write("														<span class=\"screen_out\">레이어 닫기</span>\r\n");
      out.write("													</button>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"check_view\">\r\n");
      out.write("													<input type=\"hidden\" id=\"consentHidden\" name=\"consent[1]\"\r\n");
      out.write("														value=\"\"> <label class=\" check_agree label_block\">\r\n");
      out.write("														<input type=\"checkbox\" name=\"hiddenCheck\"> <span\r\n");
      out.write("														class=\"ico\"></span>개인정보 수집·이용 동의 <span class=\"sub\">(선택)</span>\r\n");
      out.write("													</label> <a href=\"#none\" class=\"link btn_link btn_choice\">약관보기</a>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layer layer_choice\" style=\"display: none;\">\r\n");
      out.write("													<div class=\"inner_layer\">\r\n");
      out.write("														<div class=\"in_layer\">\r\n");
      out.write("															<h4 class=\"tit_layer\">\r\n");
      out.write("																개인정보 수집·이용 동의 <span class=\"sub\">(선택)</span>\r\n");
      out.write("															</h4>\r\n");
      out.write("															<div class=\"box_tbl\">\r\n");
      out.write("																<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("																	<caption class=\"screen_out\">개인정보의 수집 및 이용목적</caption>\r\n");
      out.write("																	<thead>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<th scope=\"row\" class=\"tit1\">수집 목적</th>\r\n");
      out.write("																			<th scope=\"row\" class=\"tit2\">수집 항목</th>\r\n");
      out.write("																			<th scope=\"row\" class=\"tit3\">보유 기간</th>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																	</thead>\r\n");
      out.write("																	<tbody>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<td>맞춤형 회원 서비스 제공</td>\r\n");
      out.write("																			<td>성별, 생년월일</td>\r\n");
      out.write("																			<td class=\"emph\">회원 탈퇴<br> 즉시 파기\r\n");
      out.write("																			</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																	</tbody>\r\n");
      out.write("																</table>\r\n");
      out.write("															</div>\r\n");
      out.write("															<p class=\"txt_service\">동의를 거부하시는 경우에도 서비스는 이용하실 수\r\n");
      out.write("																있습니다.</p>\r\n");
      out.write("														</div>\r\n");
      out.write("														<button type=\"button\" class=\"btn_ok\">\r\n");
      out.write("															<span class=\"txt_type\">확인</span>\r\n");
      out.write("														</button>\r\n");
      out.write("														<button type=\"button\" class=\"btn_close\">\r\n");
      out.write("															<span class=\"screen_out\">레이어 닫기</span>\r\n");
      out.write("														</button>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"check_view\">\r\n");
      out.write("													<label class=\"label_block check_agree \"> <input\r\n");
      out.write("														type=\"checkbox\" name=\"marketing\"> <span\r\n");
      out.write("														class=\"ico\"></span>무료배송, 할인쿠폰 등 혜택/정보 수신 동의 <span\r\n");
      out.write("														class=\"sub\">(선택)</span>\r\n");
      out.write("													</label>\r\n");
      out.write("													<div class=\"check_event email_sms\">\r\n");
      out.write("														<label class=\"label_block check_agree \"> <input\r\n");
      out.write("															type=\"checkbox\" name=\"sms\" value=\"n\"> <span\r\n");
      out.write("															class=\"ico\"></span>SMS\r\n");
      out.write("														</label> <label class=\"label_block check_agree \"> <input\r\n");
      out.write("															type=\"checkbox\" name=\"mailling\" value=\"n\"> <span\r\n");
      out.write("															class=\"ico\"></span>이메일\r\n");
      out.write("														</label>\r\n");
      out.write("													</div>\r\n");
      out.write("													<p class=\"sms_info\">\r\n");
      out.write("														동의 시 한 달간 [5% 적립] + [무제한 무료배송] <span class=\"sub\">(첫\r\n");
      out.write("															주문 후 적용)</span>\r\n");
      out.write("													</p>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"check_view\">\r\n");
      out.write("													<label class=\" check_agree label_block\"> <input\r\n");
      out.write("														type=\"checkbox\" value=\"n\" name=\"fourteen_chk\" required=\"\"\r\n");
      out.write("														label=\"만 14세 이상\"> <span class=\"ico\"></span>본인은 만\r\n");
      out.write("														14세 이상입니다. <span class=\"sub\">(필수)</span>\r\n");
      out.write("													</label>\r\n");
      out.write("												</div>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</tbody>\r\n");
      out.write("								</table>\r\n");
      out.write("								<div id=\"formSubmit\" class=\"form_footer\">\r\n");
      out.write("									<button type=\"button\" class=\"btn active btn_join\"\r\n");
      out.write("										onclick=\"formJoinSubmit()\">가입하기</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<iframe id=\"ifrmRnCheck\" name=\"ifrmRnCheck\" style=\"display: none;\"></iframe>\r\n");
      out.write("						<iframe id=\"ifrmHpauth\" name=\"ifrmHpauth\" style=\"display: none;\"></iframe>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/footer.jsp", out, false);
      out.write("<!-- footer부분 -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<a href=\"#top\" id=\"pageTop\">맨 위로가기</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<iframe name=\"ifrmHidden\" id=\"ifrmHidden\" src=\"about:blank\"\r\n");
      out.write("		style=\"display: none; width: 100%; height: 600px;\"></iframe>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/user/login_and_join/join.jsp(250,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KakaoJoin == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<input type=\"text\" name=\"user_id\" value=\"\" maxlength=\"16\" placeholder=\"6자 이상의 영문 혹은 영문과 숫자를 조합\"\r\n");
          out.write("														label=\"아이디\">\r\n");
          out.write("													<input id=\"posibleId\" type=\"hidden\" name=\"chk_id\" label=\"아이디중복체크\" value=\"불가능\">\r\n");
          out.write("													<a class=\"btn default\" href=\"javascript:chkId()\">중복확인</a>\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/user/login_and_join/join.jsp(256,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KakaoJoin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<input type=\"text\" name=\"user_id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kakaoId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" maxlength=\"16\" label=\"아이디\"\r\n");
          out.write("														readonly=\"readonly\">\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/user/login_and_join/join.jsp(301,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KakaoJoin==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<input type=\"text\" name=\"user_email\" value=\"\" data-email=\"\" size=\"30\" label=\"이메일\"\r\n");
          out.write("														placeholder=\"예: marketkurly@kurly.com\">\r\n");
          out.write("													<input id=\"posibleEmail\" type=\"hidden\" name=\"chk_email\" label=\"이메일중복체크\" value=\"불가능\">\r\n");
          out.write("													<a href=\"javascript:void(0)\"\r\n");
          out.write("														onclick=\"chkEmail()\" class=\"btn default\">중복확인</a>\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/user/login_and_join/join.jsp(308,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KakaoJoin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<input type=\"text\" name=\"user_email\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kakaoEmail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" data-email=\"\" size=\"30\" label=\"이메일\"\r\n");
          out.write("														readonly=\"readonly\">\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
