/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-17 12:25:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user.login_005fand_005fjoin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/secondk/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/marketKurlyty/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1632676361414L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/top.jsp", out, false);
      out.write("<!-- 기본 필요 meta, css는 include로 받아옴 -->\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("<!-- 여기부터 해당 페이지의 css 추가하면 됨-->\r\n");
      out.write("<link rel=\"styleSheet\" href=\"style/ItemListStyle.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/style/mykurly/coupon.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${FailMessage != null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("	alert(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${FailMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("Kakao.init('e843248c5d13b454b09013d97687a1b6');\r\n");
      out.write("console.log(Kakao.isInitialized());\r\n");
      out.write("function KakaoLogin(){\r\n");
      out.write("	var kakaoOk=null;\r\n");
      out.write("	window.Kakao.Auth.login({\r\n");
      out.write("		success:(auth)=>{\r\n");
      out.write("			console.log(\"정상적으로 로그인 되었습니다.\",auth)\r\n");
      out.write("			window.Kakao.API.request({\r\n");
      out.write("				url:'/v2/user/me',\r\n");
      out.write("				success:(res)=>{\r\n");
      out.write("					const kakao_account=res.id;\r\n");
      out.write("					console.log(kakao_account);\r\n");
      out.write("					console.log(res);\r\n");
      out.write("					console.log(res.kakao_account.email);\r\n");
      out.write("					console.log(res.kakao_account.profile.nickname);\r\n");
      out.write("					document.kakaoForm.kakaoId.value=res.id;\r\n");
      out.write("					document.kakaoForm.kakaoEmail.value=res.kakao_account.email;\r\n");
      out.write("					document.kakaoForm.kakaoNickName.value=res.kakao_account.profile.nickname;\r\n");
      out.write("					document.kakaoForm.submit();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		},\r\n");
      out.write("		fail:(err)=>{\r\n");
      out.write("			console.error(err)\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("//판별문\r\n");
      out.write("function formLoginSubmit(){\r\n");
      out.write("\r\n");
      out.write("	if (document.frmMember.user_id.value == \"\") {\r\n");
      out.write("		alert(\"아이디를 입력하세요.\");\r\n");
      out.write("		document.frmMember.user_id.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	else if (document.frmMember.user_pw.value == \"\") {\r\n");
      out.write("		alert(\"비밀번호 입력하세요\");\r\n");
      out.write("		document.frmMember.user_id.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	else{\r\n");
      out.write("		document.frmMember.submit();\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	$(\"input[name=user_id]\").on(\"keyup\",function(){\r\n");
      out.write("		$(this).val( $(this).val().replace(/[ㄱ-ㅎㅏ-ㅣ가-힣]/gi,\"\") );\r\n");
      out.write("	})\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".btn_kakao{\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("    background-color: #F8DF00;\r\n");
      out.write("}\r\n");
      out.write(".btn_kakao .kakao_type{\r\n");
      out.write("	color: #000000;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 51px;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write(".kakaoLogo{\r\n");
      out.write("	float:left;\r\n");
      out.write("	width:50px;\r\n");
      out.write("	height:50px;\r\n");
      out.write("	overflow:hidden;\r\n");
      out.write("	margin-left:0px;\r\n");
      out.write("	margin-top:2px;\r\n");
      out.write("	margin-right:0px;\r\n");
      out.write("}\r\n");
      out.write(".kakaoLogo img{\r\n");
      out.write("	object-fit:cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"main-index\" oncontextmenu=\"return false\" ondragstart=\"return false\">\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrap\" class=\"\">\r\n");
      out.write("		<div id=\"pos_scroll\"></div>\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/header.jsp", out, false);
      out.write("<!-- header부분 -->\r\n");
      out.write("			<div id=\"main\">\r\n");
      out.write("				<div id=\"content\">\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/sidemenu.jsp", out, false);
      out.write("<!-- 오른쪽 스크롤메뉴 부분 -->\r\n");
      out.write("					<div id=\"content\">\r\n");
      out.write("						<form id=\"kakaoForm\" name=\"kakaoForm\" action=\"kakaoLogin.do\" method=\"post\">\r\n");
      out.write("							<input id=\"kakaoId\" type=\"hidden\" name=\"kakaoId\">\r\n");
      out.write("							<input id=\"kakaoEmail\" type=\"hidden\" name=\"kakaoEmail\">\r\n");
      out.write("							<input id=\"kakaoNickName\" type=\"hidden\" name=\"kakaoNickName\">\r\n");
      out.write("						</form>\r\n");
      out.write("						<div id=\"qnb\" class=\"quick-navigation\"></div>\r\n");
      out.write("						<div class=\"section_login\">\r\n");
      out.write("							<h3 class=\"tit_login\">로그인</h3>\r\n");
      out.write("							<div class=\"write_form\">\r\n");
      out.write("								<div class=\"write_view login_view\">\r\n");
      out.write("								\r\n");
      out.write("									<form method=\"post\" name=\"frmMember\" action=\"login.do\">\r\n");
      out.write("									\r\n");
      out.write("										<input type=\"text\" name=\"user_id\" size=\"20\" tabindex=\"1\" placeholder=\"아이디를 입력해주세요\">\r\n");
      out.write("										<input type=\"password\" name=\"user_pw\" size=\"20\" tabindex=\"2\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("										\r\n");
      out.write("										<div class=\"checkbox_save\">\r\n");
      out.write("											<div class=\"login_search\">\r\n");
      out.write("												<a href=\"/shop/member/find_id.php\" class=\"link\">아이디 찾기</a>\r\n");
      out.write("												<span class=\"bar\"></span>\r\n");
      out.write("												<a href=\"/shop/member/find_pwd.php\" class=\"link\">비밀번호 찾기</a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<a class=\"btn_type1\" onclick=\"javascript:formLoginSubmit()\" href=\"#\">\r\n");
      out.write("											<span class=\"txt_type\">로그인</span>\r\n");
      out.write("										</a>\r\n");
      out.write("									</form>\r\n");
      out.write("									<a href=\"join.do\" class=\"btn_type2 btn_member\">\r\n");
      out.write("									<span class=\"txt_type\">회원가입</span></a>\r\n");
      out.write("									<a href=\"#\" onclick=\"KakaoLogin()\" class=\"btn_type2 btn_kakao\">\r\n");
      out.write("										<span class=\"kakaoLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/kakaoLogo.png\"></span>\r\n");
      out.write("										<span class=\"kakao_type\">카카오 로그인</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../default/footer.jsp", out, false);
      out.write("<!-- footer부분 -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<a href=\"#top\" id=\"pageTop\">맨 위로가기</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<iframe name=\"ifrmHidden\" id=\"ifrmHidden\" src=\"about:blank\"\r\n");
      out.write("		style=\"display: none; width: 100%; height: 600px;\"></iframe>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
