/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-05 10:15:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admin.default_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sideMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<div id=\"layoutSidenav\">\r\n");
      out.write("		<div id=\"layoutSidenav_nav\">\r\n");
      out.write("			<nav class=\"sb-sidenav accordion sb-sidenav-dark\" id=\"sidenavAccordion\">\r\n");
      out.write("				<div class=\"sb-sidenav-menu\">\r\n");
      out.write("					<div class=\"nav\">\r\n");
      out.write("						<!-- Core -->\r\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">Core</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- DashBoard -->\r\n");
      out.write("						<a class=\"nav-link\" href=\"admin_index.mdo\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-tachometer-alt\"></i>\r\n");
      out.write("							</div> Dashboard\r\n");
      out.write("						</a>\r\n");
      out.write("						\r\n");
      out.write("						<!-- interface -->\r\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">메뉴</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- 상품관리 -->\r\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("							data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\"\r\n");
      out.write("							aria-controls=\"collapseLayouts\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-columns\"></i>\r\n");
      out.write("							</div> 상품관리\r\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-static.html\">상품조회/수정</a>\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-sidenav-light.html\">상품/등록</a>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- 판매관리 -->\r\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("							data-bs-target=\"#collapseLayouts1\" aria-expanded=\"false\"\r\n");
      out.write("							aria-controls=\"collapseLayouts\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-columns\"></i>\r\n");
      out.write("							</div> 판매관리\r\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts1\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-static.html\">취소관리</a>\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-sidenav-light.html\">환불관리</a>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- 정산관리 -->\r\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("							data-bs-target=\"#collapseLayouts2\" aria-expanded=\"false\"\r\n");
      out.write("							aria-controls=\"collapseLayouts\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-columns\"></i>\r\n");
      out.write("							</div> 정산관리\r\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts2\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-static.html\">정산내역</a>\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-sidenav-light.html\">주별정산</a>\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-sidenav-light.html\">월별정산</a>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- 카테고리 -->\r\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("							data-bs-target=\"#collapseLayouts3\" aria-expanded=\"false\"\r\n");
      out.write("							aria-controls=\"collapseLayouts\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-columns\"></i>\r\n");
      out.write("							</div> 카테고리\r\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts3\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-static.html\">상위카테고리</a>\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-sidenav-light.html\">중위카테고리</a>\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-sidenav-light.html\">하위카테고리</a>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 게시글 -->\r\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("							data-bs-target=\"#collapseLayouts4\" aria-expanded=\"false\"\r\n");
      out.write("							aria-controls=\"collapseLayouts\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-columns\"></i>\r\n");
      out.write("							</div> 게시글\r\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts4\"\r\n");
      out.write("							aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-static.html\">공지사항</a> <a\r\n");
      out.write("									class=\"nav-link\" href=\"layout-sidenav-light.html\">자주하는 질문</a> <a\r\n");
      out.write("									class=\"nav-link\" href=\"layout-sidenav-light.html\">1:1문의</a>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 게시글 -->\r\n");
      out.write("\r\n");
      out.write("						<!-- 리뷰관리 -->\r\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("							data-bs-target=\"#collapseLayouts5\" aria-expanded=\"false\"\r\n");
      out.write("							aria-controls=\"collapseLayouts\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-columns\"></i>\r\n");
      out.write("							</div> 리뷰관리\r\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts5\"\r\n");
      out.write("							aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("								<a class=\"nav-link\" href=\"layout-static.html\">리뷰</a> <a\r\n");
      out.write("									class=\"nav-link\" href=\"layout-sidenav-light.html\">뮨의</a>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!--회원/관리자  -->\r\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("							data-bs-target=\"#collapsePages\" aria-expanded=\"false\"\r\n");
      out.write("							aria-controls=\"collapsePages\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-book-open\"></i>\r\n");
      out.write("							</div> 회원/관리자\r\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"collapse\" id=\"collapsePages\" aria-labelledby=\"headingTwo\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav accordion\" id=\"sidenavAccordionPages\">\r\n");
      out.write("								\r\n");
      out.write("								<!-- 회원 -->\r\n");
      out.write("								<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("									data-bs-target=\"#pagesCollapseAuth\" aria-expanded=\"false\"\r\n");
      out.write("									aria-controls=\"pagesCollapseAuth\"> 회원\r\n");
      out.write("									<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("										<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"collapse\" id=\"pagesCollapseAuth\"\r\n");
      out.write("									aria-labelledby=\"headingOne\"\r\n");
      out.write("									data-bs-parent=\"#sidenavAccordionPages\">\r\n");
      out.write("									<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("										<a class=\"nav-link\" href=\"admin_userList.mdo\">회원관리</a>\r\n");
      out.write("										<a class=\"nav-link\" href=\"password.html\">약관관리</a>\r\n");
      out.write("									</nav>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!--회원 -->\r\n");
      out.write("								\r\n");
      out.write("								<!-- 매니저관리 -->\r\n");
      out.write("								<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("									data-bs-target=\"#pagesCollapseError\" aria-expanded=\"false\"\r\n");
      out.write("									aria-controls=\"pagesCollapseError\"> 매니저관리\r\n");
      out.write("									<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("										<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"collapse\" id=\"pagesCollapseError\"\r\n");
      out.write("									aria-labelledby=\"headingOne\"\r\n");
      out.write("									data-bs-parent=\"#sidenavAccordionPages\">\r\n");
      out.write("									<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("										<a class=\"nav-link\" href=\"admin_adminList.mdo\">매니저관리/등록</a>\r\n");
      out.write("										<a class=\"nav-link\" href=\"admin_join.mdo\">매니저관리등록(임시)</a>\r\n");
      out.write("\r\n");
      out.write("									</nav>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- 매니저관리 -->\r\n");
      out.write("\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- ADDONS -->\r\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">Addons</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- Charts -->\r\n");
      out.write("						<a class=\"nav-link\" href=\"charts.html\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-chart-area\"></i>\r\n");
      out.write("							</div> Charts\r\n");
      out.write("							\r\n");
      out.write("						<!-- Tables -->\r\n");
      out.write("						</a> <a class=\"nav-link\" href=\"tables.html\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-table\"></i>\r\n");
      out.write("							</div> Tables\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sb-sidenav-footer\">\r\n");
      out.write("					<div class=\"small\">Market Kurlyty</div>\r\n");
      out.write("					Admin_index\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
