/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-05 10:17:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Admin Index</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../user/default/top.jsp", out, false);
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/style/admin/styles.css\"/>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("function zip(){\r\n");
      out.write("	var myAddress;\r\n");
      out.write("	var myZipcode;\r\n");
      out.write("	new daum.Postcode({\r\n");
      out.write("		oncomplete:function(data){\r\n");
      out.write("			myAddress=data.address;\r\n");
      out.write("			myZipcode=data.zonecode;\r\n");
      out.write("			$(\"#zip\").val(myZipcode)\r\n");
      out.write("			$(\"#addr1\").val(myAddress);\r\n");
      out.write("			$(\".hid\").attr(\"class\",\".addressShow\");\r\n");
      out.write("		}\r\n");
      out.write("	}).open();\r\n");
      out.write("}\r\n");
      out.write("function validateEmail(email){\r\n");
      out.write("	var emailReg = /^(([^<>()\\[\\]\\.,;:\\s@\\\"]+(\\.[^<>()\\[\\]\\.,;:\\s@\\\"]+)*)|(\\\".+\\\"))@(([^<>()[\\]\\.,;:\\s@\\\"]+\\.)+[^<>()[\\]\\.,;:\\s@\\\"]{2,})$/i;\r\n");
      out.write("	return emailReg.test(email);\r\n");
      out.write("}\r\n");
      out.write("function formJoinSubmit(){\r\n");
      out.write("\r\n");
      out.write("	if(document.frmAdmin.admin_id.value==\"\"){\r\n");
      out.write("		alert(\"아이디를 입력하세요.\");\r\n");
      out.write("		document.frmAdmin.admin_id.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(document.frmAdmin.chk_id.value==\"불가능\"){\r\n");
      out.write("		alert(\"중복된 아이디는 사용할 수 없습니다.\");\r\n");
      out.write("		document.frmAdmin.user_id.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	if(document.frmAdmin.admin_pw.value==\"\"){\r\n");
      out.write("		alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("		document.frmAdmin.admin_pw.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(document.frmAdmin.admin_pw_check.value==\"\"){\r\n");
      out.write("		alert(\"비밀번호 확인을 입력하세요.\");\r\n");
      out.write("		document.frmAdmin.admin_pw_check.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(document.frmAdmin.admin_pw.value!=document.frmAdmin.admin_pw_check.value){\r\n");
      out.write("		alert(\"비밀번호를 다시 확인해 주세요.\");\r\n");
      out.write("		document.frmAdmin.admin_pw_check.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(document.frmAdmin.admin_name.value==\"\"){\r\n");
      out.write("		alert(\"이름을 입력하세요.\");\r\n");
      out.write("		document.frmAdmin.admin_name.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(document.frmAdmin.admin_email.value==\"\"){\r\n");
      out.write("		alert(\"이메일을 입력하세요.\");\r\n");
      out.write("		document.frmAdmin.admin_email.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(!validateEmail(document.frmAdmin.admin_email.value)){\r\n");
      out.write("		alert(\"올바른 이메일을 입력해 주세요.\");\r\n");
      out.write("		document.frmAdmin.admin_email.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(document.frmAdmin.admin_phone.value==\"\"){\r\n");
      out.write("		alert(\"전화번호를 입력하세요.\");\r\n");
      out.write("		document.frmAdmin.admin_phone.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(document.frmAdmin.admin_address1.value==\"\"){\r\n");
      out.write("		alert(\"주소를 입력하세요.\");\r\n");
      out.write("		document.frmAdmin.admin_address1.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	if(document.frmAdmin.admin_address2.value==\"\"){\r\n");
      out.write("		alert(\"상세주소를 입력하세요.\");\r\n");
      out.write("		document.frmAdmin.admin_address2.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	document.frmAdmin.submit();\r\n");
      out.write("}\r\n");
      out.write(" function chkId(){\r\n");
      out.write("	var id = document.frmAdmin.admin_id.value;\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"idCheck.mdo?admin_id=\"+id,\r\n");
      out.write("		datatype:\"json\",\r\n");
      out.write("		success:function(res){\r\n");
      out.write("			const data = JSON.parse(res);\r\n");
      out.write("			alert(data.message);\r\n");
      out.write("			$(\"#posibleId\").val(data.usedId);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("<body class=\"sb-nav-fixed\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "default/top.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "default/sideMenu.jsp", out, false);
      out.write("\r\n");
      out.write("	<div id=\"layoutSidenav_content\">\r\n");
      out.write("		<main>\r\n");
      out.write("			<div class=\"container-fluid px-4\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"page_aticle\">\r\n");
      out.write("					<div class=\"type_form member_join \">\r\n");
      out.write("						<form id=\"form\" name=\"frmAdmin\" method=\"post\" action=\"joinProc.mdo\" novalidate=\"\">\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("							<h2>매니저 등록</h2>\r\n");
      out.write("							<table class=\"tbl_comm\">\r\n");
      out.write("								<tr class=\"fst\">\r\n");
      out.write("									<th>아이디</th>\r\n");
      out.write("									<td><input type=\"text\" name=\"admin_id\" value=\"\"\r\n");
      out.write("										maxlength=\"16\" placeholder=\"6자 이상의 영문 혹은 영문과 숫자를 조합\">\r\n");
      out.write("										<input id=\"posibleId\" type=\"hidden\" name=\"chk_id\" value=\"불가능\">\r\n");
      out.write("										<a class=\"btn default\" onclick=\"javascript:chkId()\">중복확인</a></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>비밀번호</th>\r\n");
      out.write("									<td><input type=\"password\" name=\"admin_pw\" label=\"비밀번호\"\r\n");
      out.write("										maxlength=\"16\" class=\"reg_pw\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr class=\"member_pwd\">\r\n");
      out.write("									<th>비밀번호확인</th>\r\n");
      out.write("									<td><input type=\"password\" name=\"admin_pw_check\"\r\n");
      out.write("										maxlength=\"16\" class=\"confirm_pw\"\r\n");
      out.write("										placeholder=\"비밀번호를 한번 더 입력해주세요\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>이름</th>\r\n");
      out.write("									<td><input type=\"text\" name=\"admin_name\" value=\"\"\r\n");
      out.write("										placeholder=\"이름을 입력해주세요\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>이메일</th>\r\n");
      out.write("									<td><input type=\"text\" name=\"admin_email\" value=\"\"\r\n");
      out.write("										data-email=\"\" size=\"30\" label=\"이메일\" placeholder=\"\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr class=\"field_phone\">\r\n");
      out.write("									<th>휴대폰</th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<div class=\"phone_num\">\r\n");
      out.write("											<input type=\"text\" value=\"\" pattern=\"[0-9]*\"\r\n");
      out.write("												name=\"admin_phone\" placeholder=\"숫자만 입력해주세요\" class=\"inp\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr class=\"fst\">\r\n");
      out.write("									<th>주소</th>\r\n");
      out.write("									<td><input id=\"addr1\" type=\"text\" name=\"admin_address1\"\r\n");
      out.write("										value=\"\">\r\n");
      out.write("										<a class=\"btn default\" onclick=\"javascript:zip()\">주소검색</a><br>\r\n");
      out.write("									<br> <input id=\"addr2\" type=\"text\" name=\"admin_address2\"\r\n");
      out.write("										value=\"\" placeholder=\"나머지 주소를 입력해주세요\"></td>\r\n");
      out.write("\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"select_sex\">\r\n");
      out.write("									<th>직급</th>\r\n");
      out.write("									<td><label class=\"\"> <input type=\"radio\"\r\n");
      out.write("											name=\"admin_position\" value=\"master\"> <span\r\n");
      out.write("											class=\"ico\"></span>Master\r\n");
      out.write("									</label> <label class=\"\"> <input type=\"radio\"\r\n");
      out.write("											name=\"admin_position\" value=\"senior\"> <span\r\n");
      out.write("											class=\"ico\"></span>Senior\r\n");
      out.write("									</label> <label class=\"checked\"> <input type=\"radio\"\r\n");
      out.write("											name=\"admin_position\" value=\"junior\" checked=\"checked\">\r\n");
      out.write("											<span class=\"ico\"></span>Junior\r\n");
      out.write("									</label></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("							<div id=\"formSubmit\" class=\"form_footer\">\r\n");
      out.write("								<button type=\"button\" class=\"btn active btn_join\"\r\n");
      out.write("									onclick=\"formJoinSubmit()\">가입하기</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "default/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"js/scripts.js\"> </script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"assets/demo/chart-area-demo.js\"></script>\r\n");
      out.write("	<script src=\"assets/demo/chart-bar-demo.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"js/datatables-simple-demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
